//
//  AllBands.swift
//  Lolla Lineup
//
//  Created by jcysewski on 4/7/16.
//  Copyright © 2016 jcysewski. All rights reserved.
//

import UIKit

class AllBands: UIViewController, UITableViewDataSource, UITableViewDelegate
{
    @IBOutlet weak var allBandsTableView: UITableView!
    var arrayOfAllBands : [DetailBandClass] = []
    
    //let musicNotes = UIImage(named: "music-notes")!
    //let imageView = UIImageView(image:musicNotes)
    
    var arrayOfLetters = ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"]

    

    override func viewDidLoad()
    {
        super.viewDidLoad()
        //navigationItem.title = "Lolla Lineup 2016"
        //navigationItem.titleView = image
        //self.navigationItem.titleView = imageView
        let image = UIImage(named: "lolla")
        navigationItem.titleView = UIImageView(image: image)
        let imageView = UIImageView(frame: CGRect(x: 0, y: 0, width: 40, height: 40))
        imageView.contentMode = .ScaleAspectFit
        
//        if section.init(0)
//        {
//            
//        }
//        
        
        
        allBandsTableView.dataSource = self
        allBandsTableView.delegate = self
        UITabBarItem.appearance().setTitleTextAttributes([NSForegroundColorAttributeName: UIColor.grayColor()], forState:.Normal)
        
        UITabBarItem.appearance().setTitleTextAttributes([NSForegroundColorAttributeName: UIColor.redColor()], forState:.Selected)
        
        //A
        arrayOfAllBands.append(DetailBandClass(Name: "AC Slater", Genre: "Electro House", SongOneURL: "https://www.youtube.com/watch?v=Z-O0Z2icWM0", SongTwoURL: "https://www.youtube.com/watch?v=KtsJdisuFgw", SongThreeURL: "https://www.youtube.com/watch?v=Xhb0wepHdzs", SongFourURL: "https://www.youtube.com/watch?v=xHTbqAfFbVo", SongFiveURL: "https://www.youtube.com/watch?v=PRqRTtyKPMg", SongOneName: "Calm Down", SongTwoName: "Jack Got Jacked (Jack Beats Remix)", SongThreeName: "Up Against The Wall feat. Lismore (Wonk Remix)", SongFourName: "Bass Inside", SongFiveName: "U Got 2", Day: "Day 3"))
        arrayOfAllBands.append(DetailBandClass(Name: "Adventure Club", Genre: "Electro House", SongOneURL: "https://www.youtube.com/watch?v=ZeaIvjoH1FY", SongTwoURL: "https://www.youtube.com/watch?v=09wdQP1FFR0", SongThreeURL: "https://www.youtube.com/watch?v=4ZYm0anhvLg", SongFourURL: "https://www.youtube.com/watch?v=WinkoZiOYQc", SongFiveURL: "https://www.youtube.com/watch?v=_y8p6uQDH4s", SongOneName: "Crave You", SongTwoName: "Gold (feat. Yuna)", SongThreeName: " Retro City", SongFourName: "Wonder (Feat. The Kite String Tangle)", SongFiveName: "Rise & Fall (feat. Krewella)", Day: "Day 4"))
        arrayOfAllBands.append(DetailBandClass(Name: "Alessia Cara", Genre: "Pop", SongOneURL: "https://www.youtube.com/watch?v=UKp2CrfmVfw", SongTwoURL: "https://www.youtube.com/watch?v=De30ET0dQpQ", SongThreeURL: "https://www.youtube.com/watch?v=Em7vc8NWUNY", SongFourURL: "https://www.youtube.com/watch?v=qbIaPaB9LDk", SongFiveURL: "https://www.youtube.com/watch?v=4b2M5K7sbc0", SongOneName: "Here", SongTwoName: "Wild Things", SongThreeName: "Scars to Your Beautiful", SongFourName: "Seventeen", SongFiveName: "River of Tears", Day: "Day 2"))
        arrayOfAllBands.append(DetailBandClass(Name: "Alina Baraz", Genre: "Fantasy", SongOneURL: "https://www.youtube.com/watch?v=NiqtgWWL6u8", SongTwoURL: "https://www.youtube.com/watch?v=D5q2eRU5Y5c", SongThreeURL: "https://www.youtube.com/watch?v=MUmjKCjeu1A", SongFourURL: "https://www.youtube.com/watch?v=p6_vULXtMig", SongFiveURL: "https://www.youtube.com/watch?v=JrHw9BDa3OE", SongOneName: "Fantasy", SongTwoName: "Fantasy - Felix Jaehn Remix ", SongThreeName: "Make You Feel", SongFourName: "Fantasy - Vices Remix", SongFiveName: " Pretty Thoughts", Day: "Day 3"))
        arrayOfAllBands.append(DetailBandClass(Name: "Alle Farben", Genre: "Pop", SongOneURL: "https://www.youtube.com/watch?v=HC1MmjPu3Xo", SongTwoURL: "https://www.youtube.com/watch?v=okBwFEz0TRI", SongThreeURL: "https://www.youtube.com/watch?v=zQAr3__aSn0", SongFourURL: "https://www.youtube.com/watch?v=V1Al3wMiEek", SongFiveURL: "https://www.youtube.com/watch?v=jGQWafRX7IE", SongOneName: "She Moves", SongTwoName: "Sometimes", SongThreeName: "She Moves - Acoustic Guitar Version", SongFourName: "Get High", SongFiveName: "Danse (Drauf & Dran Remix)", Day: "Day 1"))
        arrayOfAllBands.append(DetailBandClass(Name: "Alunageorge", Genre: "Electronic", SongOneURL: "https://www.youtube.com/watch?v=VfCSx5641U4", SongTwoURL: "https://www.youtube.com/watch?v=aBn7bjy9c4U", SongThreeURL: "https://www.youtube.com/watch?v=7d_HD89ZlJE", SongFourURL: "https://www.youtube.com/watch?v=wecvxQElEU0", SongFiveURL: "https://www.youtube.com/watch?v=gfVfXCSYWd0", SongOneName: "Your Drums, Your Love", SongTwoName: "You Know You Like It", SongThreeName: "Attracting Flies", SongFourName: "Supernatural", SongFiveName: "Outlines", Day: "Day 1"))
        arrayOfAllBands.append(DetailBandClass(Name: "Asap Ferg", Genre: "Hip Hop", SongOneURL: "https://www.youtube.com/watch?v=iXZxipry6kE", SongTwoURL: "https://www.youtube.com/watch?v=WjlkvM7mz1U", SongThreeURL: "https://www.youtube.com/watch?v=jkHI1hGvWRY", SongFourURL: "https://www.youtube.com/watch?v=hKFRwLIGri4", SongFiveURL: "https://www.youtube.com/watch?v=E8hzJpeRLG0", SongOneName: "Shabba", SongTwoName: "Hood Pope", SongThreeName: "Work Remix", SongFourName: "Let It Go", SongFiveName: "Dump Dump", Day: "Day 2"))
        arrayOfAllBands.append(DetailBandClass(Name: "Audien", Genre: "Electronic Rock", SongOneURL: "https://www.youtube.com/watch?v=9A3z5hmWUoY", SongTwoURL: "https://www.youtube.com/watch?v=_sDbRhC7rm8", SongThreeURL: "https://www.youtube.com/watch?v=Xr2DYH0zcZo", SongFourURL: "https://www.youtube.com/watch?v=ys7FfXtz_aQ", SongFiveURL: "https://www.youtube.com/watch?v=UhZlO4IpEP8", SongOneName: "Leaving You - Radio Edit", SongTwoName: "Something Better", SongThreeName: "Circles - Original Mix", SongFourName: "Hindsight", SongFiveName: "Wayfarer", Day: "Day 2"))
        arrayOfAllBands.append(DetailBandClass(Name: "Aurora", Genre: "Pop", SongOneURL: "https://www.youtube.com/watch?v=06ht9MyJLT4", SongTwoURL: "https://www.youtube.com/watch?v=d_HlPboLRL8", SongThreeURL: "https://www.youtube.com/watch?v=SYKU7DfEJT4", SongFourURL: "https://www.youtube.com/watch?v=5AWHALoCzPM", SongFiveURL: "https://www.youtube.com/watch?v=FA39yqwnX98", SongOneName: "Running With The Wolves", SongTwoName: "Runaway", SongThreeName: "Half The World Away", SongFourName: "Under Stars", SongFiveName: "Ordinary World", Day: "Day 4"))
        arrayOfAllBands.append(DetailBandClass(Name: "Auto Lux", Genre: "Pop/Rock", SongOneURL: "https://www.youtube.com/watch?v=uZL91Uv5e8g", SongTwoURL: "https://www.youtube.com/watch?v=AogGLXkUuvQ", SongThreeURL: "https://www.youtube.com/watch?v=0uGt1n3xERo", SongFourURL: "https://www.youtube.com/watch?v=SD67M_ZpJYk", SongFiveURL: "https://www.youtube.com/watch?v=c1GfAfcgUw4", SongOneName: "Turnstile Blues", SongTwoName: "Angry Candy", SongThreeName: "Sugarless", SongFourName: "Subzero Fun", SongFiveName: "Here Comes Everybody", Day: "Day 1"))
        //B
        arrayOfAllBands.append(DetailBandClass(Name: "Bad Royale", Genre: "DJ", SongOneURL: "https://www.youtube.com/watch?v=Q7gpn6wOTuo", SongTwoURL: "https://www.youtube.com/watch?v=KpU93h4wFSk", SongThreeURL: "https://www.youtube.com/watch?v=_9vdwJn6kPY", SongFourURL: "https://www.youtube.com/watch?v=FuwQkx21CsA", SongFiveURL: "https://www.youtube.com/watch?v=wcZyG_4AOeA", SongOneName: "King is Back feat. Big Ali - Bad Royale Remix", SongTwoName: "Pop (feat. Dominique Young Unique)", SongThreeName: "One Puff", SongFourName: "Move Like (feat. Richie Loop)", SongFiveName: "Bounce With Me (feat. Clinton Sky)", Day: "Day 1"))
//        Baid
//        arrayOfAllBands.append(DetailBandClass(Name: "Baid", Genre: "", SongOneURL: "", SongTwoURL: "", SongThreeURL: "", SongFourURL: "", SongFiveURL: "", SongOneName: "", SongTwoName: "", SongThreeName: "", SongFourName: "", SongFiveName: "", Day: ""))
        arrayOfAllBands.append(DetailBandClass(Name: "Banners", Genre: "Alternative Rock/ Pop", SongOneURL: "https://www.youtube.com/watch?v=ZXorliBQMxg", SongTwoURL: "https://www.youtube.com/watch?v=uaLblVmnNL4", SongThreeURL: "https://www.youtube.com/watch?v=U5wjOYg3SJQ", SongFourURL: "https://www.youtube.com/watch?v=6pF4VjwrkVg", SongFiveURL: "https://www.youtube.com/watch?v=0Tz-XVymk04", SongOneName: "Start A Riot", SongTwoName: "Shine A Light", SongThreeName: "Ghosts", SongFourName: "Gold Dust", SongFiveName: "Back When We Had Nothing", Day: "Day 4"))
        arrayOfAllBands.append(DetailBandClass(Name: "Bas", Genre: "Rap", SongOneURL: "https://www.youtube.com/watch?v=YyALkCHSh_0", SongTwoURL: "https://www.youtube.com/watch?v=sF--UJ3zEO4", SongThreeURL: "https://www.youtube.com/watch?v=70x4yfWpLb0", SongFourURL: "https://www.youtube.com/watch?v=E2xEfMyBtUg", SongFiveURL: "https://www.youtube.com/watch?v=WCWubSL5LeE", SongOneName: "House Wives", SongTwoName: "Aethalia", SongThreeName: "Night Job", SongFourName: "My Nigga Just Made Bail", SongFiveName: "Lit - Bonus", Day: "Day 1"))
        arrayOfAllBands.append(DetailBandClass(Name: "Bastille", Genre: "Rock", SongOneURL: "https://www.youtube.com/watch?v=F90Cw4l-8NY", SongTwoURL: "https://www.youtube.com/watch?v=MGR4U7W1dZU", SongThreeURL: "https://www.youtube.com/watch?v=1E36WU9Wzf4", SongFourURL: "https://www.youtube.com/watch?v=qoNYlV07Cf8", SongFiveURL: "https://www.youtube.com/watch?v=ZCTDKLjdok4", SongOneName: "Pompeii", SongTwoName: "Things We Lost in the Fire", SongThreeName: "Flaws", SongFourName: "Bad Blood", SongFiveName: "Of The Night", Day: "Day 1"))
        arrayOfAllBands.append(DetailBandClass(Name: "Big Gigantic", Genre: "Hip Hop", SongOneURL: "https://www.youtube.com/watch?v=xPrgVald-fc", SongTwoURL: "https://www.youtube.com/watch?v=y3Ut46W52h8", SongThreeURL: "https://www.youtube.com/watch?v=qlBUMXVZhMA", SongFourURL: "https://www.youtube.com/watch?v=nO0ZuNSFduc", SongFiveURL: "https://www.youtube.com/watch?v=RNp0KlJX6JE", SongOneName: "Sky High", SongTwoName: "Its Goin Down", SongThreeName: "Thinking Out Loud", SongFourName: "Lucid Dreams", SongFiveName: "Fire It Up", Day: "Day 3"))
        arrayOfAllBands.append(DetailBandClass(Name: "Big Grams", Genre: "Hip Hop", SongOneURL: "https://www.youtube.com/watch?v=xpmE0Qiup3U", SongTwoURL: "https://www.youtube.com/watch?v=djbFQKzkiRg", SongThreeURL: "https://www.youtube.com/watch?v=pIG2_N1drc4", SongFourURL: "https://www.youtube.com/watch?v=hruW7-mYWhY", SongFiveURL: "https://www.youtube.com/watch?v=ajJDcded23g", SongOneName: "Lights On", SongTwoName: "Fell In the Sun", SongThreeName: "Goldmine Junkie", SongFourName: "Born to Shine", SongFiveName: "Run For Your Life", Day: "Day 3"))
        arrayOfAllBands.append(DetailBandClass(Name: "Bloc Party", Genre: "Rock", SongOneURL: "https://www.youtube.com/watch?v=vdkmhquF60o", SongTwoURL: "https://www.youtube.com/watch?v=2R6S5CJWlco", SongThreeURL: "https://www.youtube.com/watch?v=-oRlpGyI1rg", SongFourURL: "https://www.youtube.com/watch?v=CdBt3n1MtFM", SongFiveURL: "https://www.youtube.com/watch?v=dzZQJZdcCU4", SongOneName: "Banquet", SongTwoName: "Helicopter", SongThreeName: "This Modern Love", SongFourName: "Like Eating Glass", SongFiveName: "So Here We Are", Day: "Day 4"))
        arrayOfAllBands.append(DetailBandClass(Name: "Bob Moses", Genre: "Electric", SongOneURL: "https://www.youtube.com/watch?v=R9Fv4nW0KaM", SongTwoURL: "https://www.youtube.com/watch?v=NAS5Z1GvxrQ", SongThreeURL: "https://www.youtube.com/watch?v=33uyeDpMBlY", SongFourURL: "https://www.youtube.com/watch?v=MzKrszohZVY", SongFiveURL: "https://www.youtube.com/watch?v=hyAoQAzwX5g", SongOneName: "Too Much Is Never Enough", SongTwoName: "Tearing Me Up", SongThreeName: "All I Want", SongFourName: "I Ain’t Gonna Be The First To Cry", SongFiveName: "Grace", Day: "Day 1"))
        arrayOfAllBands.append(DetailBandClass(Name: "BoomBox Cartel", Genre: "Electric", SongOneURL: "https://www.youtube.com/watch?v=Mt0bFWfqsDg", SongTwoURL: "https://www.youtube.com/watch?v=2odMhhbs4AI", SongThreeURL: "https://www.youtube.com/watch?v=3hUTH1ON-rw", SongFourURL: "https://www.youtube.com/watch?v=HL3SA-gLu-k", SongFiveURL: "https://www.youtube.com/watch?v=IQq8l4JnefI", SongOneName: "B2U (feat. Ian Everson)", SongTwoName: "Jamba", SongThreeName: "Where’s My Money", SongFourName: "Spaceless", SongFiveName: "Hysteria (“WTF Is Festival Trap” Anthem)", Day: "Day 2"))
        arrayOfAllBands.append(DetailBandClass(Name: "Bro Safari", Genre: "Dub Step", SongOneURL: "https://www.youtube.com/watch?v=XxGmgmelZV0", SongTwoURL: "https://www.youtube.com/watch?v=8o3nZQU4evo", SongThreeURL: "https://www.youtube.com/watch?v=ugLvpJWWhCA", SongFourURL: "https://www.youtube.com/watch?v=twbEV6fBNo8", SongFiveURL: "https://www.youtube.com/watch?v=bu3c8w53jA4", SongOneName: "The Drop", SongTwoName: "That A$$", SongThreeName: "Scumbag", SongFourName: "Da Worm", SongFiveName: "The Clap (feat. ETC!ETC!)", Day: "Day 2"))
        arrayOfAllBands.append(DetailBandClass(Name: "Bryson Tiller", Genre: "Hip Hop", SongOneURL: "https://www.youtube.com/watch?v=iOpJywrdCuQ", SongTwoURL: "https://www.youtube.com/watch?v=d7cVLE4SaN0", SongThreeURL: "https://www.youtube.com/watch?v=WJ47cpZE-wg", SongFourURL: "", SongFiveURL: "", SongOneName: "Exchange", SongTwoName: "Don’t (J. Louis Remix)", SongThreeName: "Dreams", SongFourName: "", SongFiveName: "", Day: "Day 4"))
        //Burns
        arrayOfAllBands.append(DetailBandClass(Name: "Burns", Genre: "DJ", SongOneURL: "https://www.youtube.com/watch?v=sMRUgw6ODDg", SongTwoURL: "https://www.youtube.com/watch?v=Q0hfrxg7fa8", SongThreeURL: "", SongFourURL: "", SongFiveURL: "", SongOneName: "Lies", SongTwoName: "First Move", SongThreeName: "", SongFourName: "", SongFiveName: "", Day: "Day 4"))
        //C
        arrayOfAllBands.append(DetailBandClass(Name: "Cashmere Cat", Genre: "DJ", SongOneURL: "https://www.youtube.com/watch?v=kxELjU3f7Z4", SongTwoURL: "https://www.youtube.com/watch?v=be-LbSaEzZQ", SongThreeURL: "https://www.youtube.com/watch?v=9RNQxY-YVKs", SongFourURL: "https://www.youtube.com/watch?v=MdoB_kYLTGw", SongFiveURL: "https://www.youtube.com/watch?v=lDWIPCTime4", SongOneName: "Mirror Maru", SongTwoName: "With Me", SongThreeName: "Kiss Kiss", SongFourName: "Adore", SongFiveName: "Paws", Day: "Day 1"))
        arrayOfAllBands.append(DetailBandClass(Name: "Chair Lift", Genre: "Syntho Pop", SongOneURL: "https://www.youtube.com/watch?v=w8HRCacAQ-4", SongTwoURL: "https://www.youtube.com/watch?v=j_aTOyFRwJ0", SongThreeURL: "https://www.youtube.com/watch?v=98XRKr19jIE", SongFourURL: "https://www.youtube.com/watch?v=mvqakws0CeU", SongFiveURL: "https://www.youtube.com/watch?v=GrM5SOGw9T8", SongOneName: "Bruises", SongTwoName: "I Belong In Your Arms", SongThreeName: "Amanaemonesia", SongFourName: "Evident Utensil", SongFiveName: "Sidewalk Safari", Day: "Day 3"))
        arrayOfAllBands.append(DetailBandClass(Name: "Cherub", Genre: "Rock", SongOneURL: "https://www.youtube.com/watch?v=E45fogGN_Y8", SongTwoURL: "https://www.youtube.com/watch?v=JZB3LTNjTWc", SongThreeURL: "https://www.youtube.com/watch?v=RRLfQL_DEfM", SongFourURL: "https://www.youtube.com/watch?v=aoUfpBYg4Ac", SongFiveURL: "", SongOneName: "Doses And Mimosas", SongTwoName: "XOXO", SongThreeName: "Disco Inferno", SongFourName: "Sucker For Love", SongFiveName: "", Day: "Day 2"))
        arrayOfAllBands.append(DetailBandClass(Name: "Chris Stapleton", Genre: "Southern Rock", SongOneURL: "https://www.youtube.com/watch?v=4zAThXFOy2c", SongTwoURL: "https://www.youtube.com/watch?v=_kBnFgLP8po", SongThreeURL: "https://www.youtube.com/watch?v=etD0Y_8vyxg", SongFourURL: "https://www.youtube.com/watch?v=ymqPEoFwhpU", SongFiveURL: "https://www.youtube.com/watch?v=6pNSOyrkX5w", SongOneName: "Tennessee Whiskey", SongTwoName: "Traveller", SongThreeName: "Nobody to Blame", SongFourName: "Whiskey and You", SongFiveName: "More Of You", Day: "Day 3"))
        arrayOfAllBands.append(DetailBandClass(Name: "City and Colour", Genre: "Acoustic", SongOneURL: "https://www.youtube.com/watch?v=mS8xDo-qM8w", SongTwoURL: "https://www.youtube.com/watch?v=NjMsWarn8BI", SongThreeURL: "https://www.youtube.com/watch?v=8rU7WPVcLmQ", SongFourURL: "https://www.youtube.com/watch?v=SBsRyktvXf0", SongFiveURL: "https://www.youtube.com/watch?v=NZIj31QHidY", SongOneName: "The Girl", SongTwoName: "Comin Home", SongThreeName: "Sleeping Sickness", SongFourName: "Hello, I’m In Delaware", SongFiveName: "Save Your Scissors", Day: "Day 1"))
        arrayOfAllBands.append(DetailBandClass(Name: "Classixx", Genre: "DJ’s", SongOneURL: "https://www.youtube.com/watch?v=kMgP0lFyVXA", SongTwoURL: "https://www.youtube.com/watch?v=1dF7YiDh6ow", SongThreeURL: "https://www.youtube.com/watch?v=Y-igh9Suess", SongFourURL: "https://www.youtube.com/watch?v=bPuB8yyPIG4", SongFiveURL: "https://www.youtube.com/watch?v=MYK3OSlj8Oo", SongOneName: "All You’re", SongTwoName: "A Stranger Love", SongThreeName: "Hanging Gardens", SongFourName: "Holding On", SongFiveName: "I’ll Get You", Day: "Day 4"))
        arrayOfAllBands.append(DetailBandClass(Name: "Cloves", Genre: "Rock", SongOneURL: "https://www.youtube.com/watch?v=1FGrjh8j8z0", SongTwoURL: "https://www.youtube.com/watch?v=F5UAvgr_Ipg", SongThreeURL: "https://www.youtube.com/watch?v=F_Jk_uQ4gSg", SongFourURL: "https://www.youtube.com/watch?v=0S7E7hczBiA", SongFiveURL: "", SongOneName: "Frail Love", SongTwoName: "Everybody’s Son", SongThreeName: "Don’t You Wait", SongFourName: "Don’t Forget About Me", SongFiveName: "", Day: "Day 1"))
        arrayOfAllBands.append(DetailBandClass(Name: "Con Brio", Genre: "Hip Hop", SongOneURL: "https://www.youtube.com/watch?v=jo-Puo61N0w", SongTwoURL: "https://www.youtube.com/watch?v=4-MNi7jwphI", SongThreeURL: "https://www.youtube.com/watch?v=WyovgZY5Vls", SongFourURL: "https://www.youtube.com/watch?v=yWE0eXnHXWI", SongFiveURL: "https://www.youtube.com/watch?v=uy1_h5VPzUk", SongOneName: "Apple", SongTwoName: "Never Be The Same", SongThreeName: "Give It All", SongFourName: "Kiss The Sun", SongFiveName: "California Cowboy", Day: "Day 2"))
        arrayOfAllBands.append(DetailBandClass(Name: "Cozz", Genre: "Rap", SongOneURL: "https://www.youtube.com/watch?v=Y7d42LJfkqQ", SongTwoURL: "https://www.youtube.com/watch?v=i8Dg6qj8L3M", SongThreeURL: "https://www.youtube.com/watch?v=6FdKK6qO6sA", SongFourURL: "https://www.youtube.com/watch?v=ObQeKIJhFuI", SongFiveURL: "https://www.youtube.com/watch?v=K4wUiGFwDPM", SongOneName: "Knock Tha Hustle - Remix", SongTwoName: "Dreams", SongThreeName: "Im Tha Man", SongFourName: "Cody Macc", SongFiveName: "Come Get It", Day: "Day 1"))
        arrayOfAllBands.append(DetailBandClass(Name: "D.R.A.M.", Genre: "Rap", SongOneURL: "https://www.youtube.com/watch?v=nUv3vM7iMTo", SongTwoURL: "https://www.youtube.com/watch?v=_ZeaSIMiB7k", SongThreeURL: "https://www.youtube.com/watch?v=rKRtyBB0Vho", SongFourURL: "https://www.youtube.com/watch?v=kdQ1Gj3y13s", SongFiveURL: "https://www.youtube.com/watch?v=EIPwOIamXmI", SongOneName: "Signals", SongTwoName: "CareTaker", SongThreeName: "I Luv It", SongFourName: "Mind Gone", SongFiveName: "2$", Day: "Day 4"))
        arrayOfAllBands.append(DetailBandClass(Name: "Danny Brown", Genre: "Hip Hop", SongOneURL: "https://www.youtube.com/watch?v=hCdgDxQbW_U", SongTwoURL: "https://www.youtube.com/watch?v=7cxC4UeZbHk", SongThreeURL: "https://www.youtube.com/watch?v=pcGGfojS58U", SongFourURL: "https://vimeo.com/91583133", SongFiveURL: "https://www.youtube.com/watch?v=NHfWY0is3rE", SongOneName: "Detroit vs Everybody", SongTwoName: "Side B", SongThreeName: "Kush Coma", SongFourName: "25 Bucks", SongFiveName: "Grown Up", Day: "Day 1"))
        arrayOfAllBands.append(DetailBandClass(Name: "Daughter", Genre: "Rock", SongOneURL: "https://www.youtube.com/watch?v=2QT5eGHCJdE", SongTwoURL: "https://www.youtube.com/watch?v=90mzH1kvznQ", SongThreeURL: "https://www.youtube.com/watch?v=aM2lObw1CbY", SongFourURL: "https://www.youtube.com/watch?v=uUWrcFpmI5U", SongFiveURL: "https://www.youtube.com/watch?v=GnkzvAXWV-0", SongOneName: "Youth", SongTwoName: "Candles", SongThreeName: "Medicine", SongFourName: "Still", SongFiveName: "Smother", Day: "Day 1"))
        arrayOfAllBands.append(DetailBandClass(Name: "Day Wave", Genre: "Rock", SongOneURL: "https://www.youtube.com/watch?v=QUVGWkRJ3Pc", SongTwoURL: "https://www.youtube.com/watch?v=vLGc0Uq5RpU", SongThreeURL: "https://www.youtube.com/watch?v=Oh1Q0283GN4", SongFourURL: "https://www.youtube.com/watch?v=83KDgjM6__c", SongFiveURL: "https://www.youtube.com/watch?v=dJRJAWBINdE", SongOneName: "Come Home Now", SongTwoName: "Total Zombies", SongThreeName: "We Try But We Don’t Fit In", SongFourName: "Dead Beat Girl", SongFiveName: "Hard To Read", Day: "Day 2"))
        arrayOfAllBands.append(DetailBandClass(Name: "Die AntWoord", Genre: "Hip Hop", SongOneURL: "https://www.youtube.com/watch?v=uMK0prafzw0", SongTwoURL: "https://www.youtube.com/watch?v=8Uee_mcxvrw", SongThreeURL: "https://www.youtube.com/watch?v=cegdR0GiJl4", SongFourURL: "https://www.youtube.com/watch?v=BXx7LZdrqHE", SongFiveURL: "https://www.youtube.com/watch?v=AIXUgtNC4Kc", SongOneName: "Ugly Boy", SongTwoName: "I Fink U Freaky", SongThreeName: "Enter The Ninja", SongFourName: "Baby’s On Fire", SongFiveName: "Fatty Boom Boom", Day: "Day 4"))
        arrayOfAllBands.append(DetailBandClass(Name: "Disclosure", Genre: "Electronic", SongOneURL: "https://www.youtube.com/watch?v=fB63ztKnGvo", SongTwoURL: "https://www.youtube.com/watch?v=93ASUImTedo", SongThreeURL: "https://www.youtube.com/watch?v=_zPlr-o-YEQ", SongFourURL: "https://www.youtube.com/watch?v=b_KfnGBtVeA", SongFiveURL: "https://www.youtube.com/watch?v=4nsKDJlpUbA", SongOneName: "Omen", SongTwoName: "Latch", SongThreeName: "You & Me", SongFourName: "Magnets", SongFiveName: "When A Fire Starts To Burn", Day: "Day 3"))
        arrayOfAllBands.append(DetailBandClass(Name: "Don Diablo", Genre: "Electronic", SongOneURL: "https://www.youtube.com/watch?v=Cbvqv19Nf0E", SongTwoURL: "https://www.youtube.com/watch?v=r6E3J4GPpjc", SongThreeURL: "https://www.youtube.com/watch?v=hVB3LNDE6pE", SongFourURL: "https://www.youtube.com/watch?v=RJOmSMQVCXg", SongFiveURL: "https://www.youtube.com/watch?v=Ue8PpA557Bc", SongOneName: "Chemicals", SongTwoName: "On My Mind", SongThreeName: "Universe", SongFourName: "Starlight", SongFiveName: "Knight Time", Day: "Day 1"))
        arrayOfAllBands.append(DetailBandClass(Name: "Drowners", Genre: "Rock", SongOneURL: "https://www.youtube.com/watch?v=VuFYXj5k8ug", SongTwoURL: "https://www.youtube.com/watch?v=b-AgW4E7cNY", SongThreeURL: "https://www.youtube.com/watch?v=SMquKngK_Fk", SongFourURL: "https://www.youtube.com/watch?v=mVj_MRGNa4c", SongFiveURL: "https://www.youtube.com/watch?v=NkP7kwMKRWo", SongOneName: "Luv, Hold Me Down", SongTwoName: "A Button On Your Blouse", SongThreeName: "Cruel Ways", SongFourName: "Unzip Your Harrington", SongFiveName: "Long Hair", Day: "Day 3"))
        arrayOfAllBands.append(DetailBandClass(Name: "Dua Lipa", Genre: "Pop", SongOneURL: "https://www.youtube.com/watch?v=-rey3m8SWQI", SongTwoURL: "https://www.youtube.com/watch?v=lwZqbQL4H4Q", SongThreeURL: "https://www.youtube.com/watch?v=Nz-dPOjK1gQ", SongFourURL: "", SongFiveURL: "", SongOneName: "Be The One", SongTwoName: "Last Dance", SongThreeName: "New Love", SongFourName: "", SongFiveName: "", Day: "Day 3"))
        arrayOfAllBands.append(DetailBandClass(Name: "Duke Dumont", Genre: "Electronic", SongOneURL: "https://www.youtube.com/watch?v=KDxJlW6cxRk", SongTwoURL: "https://www.youtube.com/watch?v=FHCYHldJi_g", SongThreeURL: "https://www.youtube.com/watch?v=FnJIb4A-DuY", SongFourURL: "https://www.youtube.com/watch?v=6oAqOFz6QsU", SongFiveURL: "https://www.youtube.com/watch?v=kv_cwzAIOHs", SongOneName: "Ocean Drive", SongTwoName: "I Got U", SongThreeName: "Need U", SongFourName: "The Giver", SongFiveName: "Won’t Look Back", Day: "Day 2"))
        arrayOfAllBands.append(DetailBandClass(Name: "Ellie Goulding", Genre: "Pop", SongOneURL: "https://www.youtube.com/watch?v=0NKUpo_xKyQ", SongTwoURL: "https://www.youtube.com/watch?v=BBxjC9w_Cj0", SongThreeURL: "https://www.youtube.com/watch?v=rNpBahr49mA", SongFourURL: "https://www.youtube.com/watch?v=5hzgS9s-tE8", SongFiveURL: "https://www.youtube.com/watch?v=CGyEd0aKWZE", SongOneName: "Lights", SongTwoName: "Love Me Like You Do", SongThreeName: "Figure 8", SongFourName: "Anything Could Happen", SongFiveName: "Burn", Day: "Day 4"))
        arrayOfAllBands.append(DetailBandClass(Name: "Excision", Genre: "Electronic", SongOneURL: "https://www.youtube.com/watch?v=8dZDdW7v4Q8", SongTwoURL: "https://www.youtube.com/watch?v=3-UAKEJDOXw", SongThreeURL: "https://www.youtube.com/watch?v=g_8cjKU2ve8", SongFourURL: "https://www.youtube.com/watch?v=3pDKFLEvd3o", SongFiveURL: "https://www.youtube.com/watch?v=fphS3QKh2ZQ", SongOneName: "Bring The Madness", SongTwoName: "Robo Kitty", SongThreeName: "CodeName X", SongFourName: "X Rated", SongFiveName: "Swagga", Day: "Day 1"))
        arrayOfAllBands.append(DetailBandClass(Name: "Fidlar", Genre: "Rock", SongOneURL: "https://www.youtube.com/watch?v=iJy8VgB83OQ", SongTwoURL: "https://www.youtube.com/watch?v=BYbJmQj5VkE", SongThreeURL: "https://www.youtube.com/watch?v=ztlZq_qqu-4", SongFourURL: "https://www.youtube.com/watch?v=BB8z08_8uhM", SongFiveURL: "https://www.youtube.com/watch?v=2mV239VN1-U", SongOneName: "40oz On Repeat", SongTwoName: "No Waves", SongThreeName: "West Coast", SongFourName: "Cheap Beer", SongFiveName: "Wake Bake Skate", Day: "Day 4"))
        arrayOfAllBands.append(DetailBandClass(Name: "FlatBush Zombies", Genre: "Hip Hop", SongOneURL: "https://www.youtube.com/watch?v=xA3Ov1RP2cw", SongTwoURL: "https://www.youtube.com/watch?v=pxplVYIN1Fc", SongThreeURL: "https://www.youtube.com/watch?v=Mhvyi1c6Gkw", SongFourURL: "https://www.youtube.com/watch?v=i9X92OV4o48", SongFiveURL: "https://www.youtube.com/watch?v=NwaE6UpMk5s", SongOneName: "New Phone, Who Dis?", SongTwoName: "This Is It", SongThreeName: "R.I.P.C.D.", SongFourName: "Your Favorite Rap Song", SongFiveName: "Bounce", Day: "Day 4"))
        arrayOfAllBands.append(DetailBandClass(Name: "Flosstrdamus", Genre: "Hip Hop", SongOneURL: "https://www.youtube.com/watch?v=LgiyMpKBl28", SongTwoURL: "https://www.youtube.com/watch?v=YUbsKY8JCvw", SongThreeURL: "https://www.youtube.com/watch?v=OcvunrplrZc", SongFourURL: "https://www.youtube.com/watch?v=imHTgWXmR7g", SongFiveURL: "https://www.youtube.com/watch?v=KNByf1o4T_8", SongOneName: "SoundClash", SongTwoName: "Drop Top", SongThreeName: "Prison Riot", SongFourName: "TTU", SongFiveName: "Mosh Pit", Day: "Day 1"))
        arrayOfAllBands.append(DetailBandClass(Name: "Flume", Genre: "Electronic", SongOneURL: "https://www.youtube.com/watch?v=-KPnyf8vwXI", SongTwoURL: "https://www.youtube.com/watch?v=6vopR3ys8Kw", SongThreeURL: "https://www.youtube.com/watch?v=X_H3cIsenBQ", SongFourURL: "https://www.youtube.com/watch?v=4fAzM5cI5FM", SongFiveURL: "https://www.youtube.com/watch?v=peRS3KGNxoY", SongOneName: "Never Be Like You", SongTwoName: "Drop The Game", SongThreeName: "Holdin On", SongFourName: "Smoke & Retribution", SongFiveName: "Insane", Day: "Day 4"))
        arrayOfAllBands.append(DetailBandClass(Name: "Foals", Genre: "Rock", SongOneURL: "https://www.youtube.com/watch?v=l_EIE5f2t6M", SongTwoURL: "https://www.youtube.com/watch?v=eYoINidnLRQ", SongThreeURL: "https://www.youtube.com/watch?v=bAsGFnLl2u0", SongFourURL: "https://www.youtube.com/watch?v=iuQQIawCqBA", SongFiveURL: "https://www.youtube.com/watch?v=m5KQOGHXkgw", SongOneName: "Mountain At My Gates", SongTwoName: "Spanish Sahara", SongThreeName: "My Number", SongFourName: "What Went Down", SongFiveName: "Prelude", Day: "Day 2"))
        arrayOfAllBands.append(DetailBandClass(Name: "Frances", Genre: "", SongOneURL: "", SongTwoURL: "", SongThreeURL: "", SongFourURL: "", SongFiveURL: "", SongOneName: "", SongTwoName: "", SongThreeName: "", SongFourName: "", SongFiveName: "", Day: ""))
        arrayOfAllBands.append(DetailBandClass(Name: "Frank Turner", Genre: "Alternative", SongOneURL: "https://www.youtube.com/watch?v=tB4Avdlz3lk", SongTwoURL: "https://www.youtube.com/watch?v=P4IZbCl6iR4", SongThreeURL: "https://www.youtube.com/watch?v=Cf5O2M5GaEA", SongFourURL: "https://www.youtube.com/watch?v=0LQVMRoglIo", SongFiveURL: "https://www.youtube.com/watch?v=F1L5zJ2afLs", SongOneName: "Get Better", SongTwoName: "The Next Storm", SongThreeName: "The Way I tend To Be", SongFourName: "Song For Josh", SongFiveName: "Recovery", Day: "Day 2"))
        arrayOfAllBands.append(DetailBandClass(Name: "Frightened Rabbit", Genre: "Rock", SongOneURL: "https://www.youtube.com/watch?v=J8fVX41-Njg", SongTwoURL: "https://www.youtube.com/watch?v=SzjERZU3wbY", SongThreeURL: "https://www.youtube.com/watch?v=KY4j8Ow-CTs", SongFourURL: "https://www.youtube.com/watch?v=y3xadvsaS_Q", SongFiveURL: "https://www.youtube.com/watch?v=aTXA_q12hKg", SongOneName: "Keep YourSelf Warm", SongTwoName: "Swim Until You Can’t See land", SongThreeName: "The WoodPile", SongFourName: "Fuck This Place", SongFiveName: "Backwards Walk", Day: "Day 2"))
        arrayOfAllBands.append(DetailBandClass(Name: "Future", Genre: "Hip Hop", SongOneURL: "https://www.youtube.com/watch?v=I8IhkhLvvho", SongTwoURL: "https://www.youtube.com/watch?v=NkfHxKw6dYg", SongThreeURL: "https://www.youtube.com/watch?v=S-T2f-136mA", SongFourURL: "https://www.youtube.com/watch?v=iJK0OGlhKF4", SongFiveURL: "https://www.youtube.com/watch?v=DXXZ3J_QIGw", SongOneName: "March Madness", SongTwoName: "Just Like Bruddas", SongThreeName: "News Or Somthn", SongFourName: "Trap Niggas", SongFiveName: "56 Nights", Day: "Day 2"))
        
        //G
        arrayOfAllBands.append(DetailBandClass(Name: "G Eazy", Genre: "Rap", SongOneURL: "https://www.youtube.com/watch?v=bSfpSOBD30U", SongTwoURL: "https://www.youtube.com/watch?v=CxnaPa8ohmM", SongThreeURL: "https://www.youtube.com/watch?v=fu7NR1qe_Mk", SongFourURL: "https://www.youtube.com/watch?v=UI9WCl4Cd8E", SongFiveURL: "https://www.youtube.com/watch?v=-3wlroM2gZ8", SongOneName: "Me Myself & I", SongTwoName: "I Mean It", SongThreeName: "Tumblr Girls", SongFourName: "Order More", SongFiveName: "You Got Me", Day: "Day 1"))
        
        arrayOfAllBands.append(DetailBandClass(Name: "Generik", Genre: "", SongOneURL: "", SongTwoURL: "", SongThreeURL: "", SongFourURL: "", SongFiveURL: "", SongOneName: "", SongTwoName: "", SongThreeName: "", SongFourName: "", SongFiveName: "", Day: ""))
        
        arrayOfAllBands.append(DetailBandClass(Name: "Ghost", Genre: "Rock", SongOneURL: "https://www.youtube.com/watch?v=-0Ao4t_fe0I", SongTwoURL: "http://www.vevo.com/watch/ghost-bc/year-zero/USUV71300503", SongThreeURL: "https://www.youtube.com/watch?v=6A-IoOEPbUs", SongFourURL: "https://www.youtube.com/watch?v=Dxr5sKyK8ys", SongFiveURL: "https://www.youtube.com/watch?v=vyQZ13jobIY", SongOneName: "Cirice", SongTwoName: "Year Zero", SongThreeName: "From The Pinnacle To The Pit", SongFourName: "Monstrance Clock", SongFiveName: "Secular Haze", Day: "Day 2"))
        arrayOfAllBands.append(DetailBandClass(Name: "Grand Theft ", Genre: "Hip Hop", SongOneURL: "https://www.youtube.com/watch?v=8T7_1nPQoS0", SongTwoURL: "https://www.youtube.com/watch?v=bTkTl8vk6Cc", SongThreeURL: "https://www.youtube.com/watch?v=wq94Jp8MJgI", SongFourURL: "https://www.youtube.com/watch?v=JRWtHcZkJMc", SongFiveURL: "https://www.youtube.com/watch?v=xD5S4BpBPcw", SongOneName: "Keep It 100", SongTwoName: "Mobbin", SongThreeName: "Quit This City", SongFourName: "Let Me Tell You Something", SongFiveName: "All The Way Up", Day: "Day 1"))
        arrayOfAllBands.append(DetailBandClass(Name: "Grimes", Genre: "Electronic", SongOneURL: "https://www.youtube.com/watch?v=c2EJMd7ZN7w", SongTwoURL: "https://www.youtube.com/watch?v=Tv9YoYCKNoE", SongThreeURL: "https://www.youtube.com/watch?v=N9XKLqGqwLA", SongFourURL: "https://www.youtube.com/watch?v=JtH68PJIQLE", SongFiveURL: "https://www.youtube.com/watch?v=1FH-q0I1fJY", SongOneName: "Kill V Maim", SongTwoName: "Flesh Without Blood", SongThreeName: "Realiti", SongFourName: "Oblivion", SongFiveName: "Genesis", Day: "Day 3"))
        arrayOfAllBands.append(DetailBandClass(Name: "Griz", Genre: "Electronic", SongOneURL: "https://www.youtube.com/watch?v=p8P28RXa3zY", SongTwoURL: "https://www.youtube.com/watch?v=y6n0XsiX_QQ", SongThreeURL: "https://www.youtube.com/watch?v=77fOPps7yus", SongFourURL: "https://www.youtube.com/watch?v=NeG89FKJEq4", SongFiveURL: "https://www.youtube.com/watch?v=UsSzq5h2-tc", SongOneName: "Stop Trippin ", SongTwoName: "Gettin’ Live", SongThreeName: "Good Times Roll", SongFourName: "A Fine Way To Die", SongFiveName: "Smash The Funk", Day: "Day 2"))
        //H
        arrayOfAllBands.append(DetailBandClass(Name: "Haelos", Genre: "Electronic", SongOneURL: "https://www.youtube.com/watch?v=uXTFP4wcjdA", SongTwoURL: "https://www.youtube.com/watch?v=KPOHKkxgPsQ", SongThreeURL: "https://www.youtube.com/watch?v=vKakNhz2ToA", SongFourURL: "https://www.youtube.com/watch?v=IY0JVKORfR4", SongFiveURL: "https://www.youtube.com/watch?v=HmzveKLF9Fk", SongOneName: "Dust", SongTwoName: "Earth Not Above", SongThreeName: "Pray", SongFourName: "SEPARATE LIVES", SongFiveName: "Ethyr", Day: "Day 2"))
        arrayOfAllBands.append(DetailBandClass(Name: "Haim", Genre: "Rock", SongOneURL: "https://www.youtube.com/watch?v=AIjVpRAXK18", SongTwoURL: "https://www.youtube.com/watch?v=eSlmgr15Yh0", SongThreeURL: "https://www.youtube.com/watch?v=Ljg6g7BAdQo", SongFourURL: "https://www.youtube.com/watch?v=kiqIush2nTA", SongFiveURL: "https://www.youtube.com/watch?v=1TffpkE2GU4", SongOneName: "Falling", SongTwoName: "My Song 5", SongThreeName: "If I Could Change Your Mind", SongFourName: "Don’t Save Me ", SongFiveName: "The Wire", Day: "Day 4"))
        arrayOfAllBands.append(DetailBandClass(Name: "Halsey", Genre: "Electronic", SongOneURL: "https://www.youtube.com/watch?v=JGulAZnnTKA", SongTwoURL: "https://www.youtube.com/watch?v=1rfSHisyHdc", SongThreeURL: "https://www.youtube.com/watch?v=b-eYbUVZedY", SongFourURL: "https://www.youtube.com/watch?v=ao4o-XRU_KM", SongFiveURL: "https://www.youtube.com/watch?v=zRHNi3QfFlE", SongOneName: "Colors", SongTwoName: "Castle", SongThreeName: "New Americana", SongFourName: "Ghost", SongFiveName: "Gasoline", Day: "Day 4"))
        arrayOfAllBands.append(DetailBandClass(Name: "Hardwell", Genre: "Electronic", SongOneURL: "https://www.youtube.com/watch?v=ppy-fgbPn2s", SongTwoURL: "https://www.youtube.com/watch?v=AQ0resnXCcE", SongThreeURL: "https://www.youtube.com/watch?v=lETmskoqh30", SongFourURL: "https://www.youtube.com/watch?v=ULwcsIPdc8w", SongFiveURL: "https://www.youtube.com/watch?v=Ox_rgDuyws8", SongOneName: "Call Me a Spaceman", SongTwoName: "Young Again", SongThreeName: "Spaceman", SongFourName: "Run Wild", SongFiveName: "Sally", Day: "Day 3"))
        arrayOfAllBands.append(DetailBandClass(Name: "Hayden James", Genre: "Electronic", SongOneURL: "https://www.youtube.com/watch?v=Hyi8Z4s2miw", SongTwoURL: "https://www.youtube.com/watch?v=MfttyNSCI-g", SongThreeURL: "https://www.youtube.com/watch?v=stNRPseb_Mg", SongFourURL: "https://www.youtube.com/watch?v=idKjrBwuWFM", SongFiveURL: "https://www.youtube.com/watch?v=C_GUj12tdtA", SongOneName: "Something About You", SongTwoName: "Permission to Love", SongThreeName: "Embrace", SongFourName: "Beginnings", SongFiveName: "No Time", Day: "Day 2"))
        arrayOfAllBands.append(DetailBandClass(Name: "Hiatus Kaiyote", Genre: "Electronic", SongOneURL: "https://www.youtube.com/watch?v=Ozr4KsZBTvQ", SongTwoURL: "https://www.youtube.com/watch?v=9ZVMViSx6Ek", SongThreeURL: "https://www.youtube.com/watch?v=2L-UbZJSfW8", SongFourURL: "https://www.youtube.com/watch?v=-Ilr1AY41AA", SongFiveURL: "https://www.youtube.com/watch?v=ya7aDtEdTTo", SongOneName: "Nakamarra", SongTwoName: "Breathing Under Water", SongThreeName: "Lace Skull", SongFourName: "By Fire", SongFiveName: "Shaolin Monk MotherFunk", Day: "Day 1"))
        arrayOfAllBands.append(DetailBandClass(Name: "Hound Mouth", Genre: "Rock", SongOneURL: "https://www.youtube.com/watch?v=Y8wifV5RYr8", SongTwoURL: "https://www.youtube.com/watch?v=hws_N4St0BU", SongThreeURL: "https://www.youtube.com/watch?v=lSccfq31t7w", SongFourURL: "https://www.youtube.com/watch?v=a6D_-1wk-MY", SongFiveURL: "https://www.youtube.com/watch?v=8cqVU7Bevic", SongOneName: "Sedona", SongTwoName: "Penitentiary", SongThreeName: "Casino", SongFourName: "Say It", SongFiveName: "My Cousin Greg", Day: "Day 3"))
        //I
        arrayOfAllBands.append(DetailBandClass(Name: "Illenium", Genre: "Electronic", SongOneURL: "https://www.youtube.com/watch?v=hgozboU7ne0", SongTwoURL: "https://www.youtube.com/watch?v=81uHlxzM6KE", SongThreeURL: "https://www.youtube.com/watch?v=Xe-KCnjp2AA", SongFourURL: "https://www.youtube.com/watch?v=m5UDehvPzLE", SongFiveURL: "https://www.youtube.com/watch?v=BfY7TfeGqV0", SongOneName: "Ill Be Your Reason", SongTwoName: "All On U", SongThreeName: "In Your Wake", SongFourName: "Drop Our Hearts", SongFiveName: "SleepWalker", Day: "Day 2"))
        //J
        arrayOfAllBands.append(DetailBandClass(Name: "J.Cole", Genre: "Hip Hop", SongOneURL: "https://www.youtube.com/watch?v=y-vQ_VsTkn0", SongTwoURL: "https://www.youtube.com/watch?v=N6PyB9Feu_k", SongThreeURL: "https://www.youtube.com/watch?v=9VzpCmRtCL0", SongFourURL: "https://www.youtube.com/watch?v=-BmKepFmBQs", SongFiveURL: "https://www.youtube.com/watch?v=-dyPeGDeS3o", SongOneName: "Lost Ones", SongTwoName: "Simba", SongThreeName: "Be Free", SongFourName: "I Get Up", SongFiveName: "Lights Please", Day: "Day 1"))
        arrayOfAllBands.append(DetailBandClass(Name: "Jack Garratt", Genre: "Pop", SongOneURL: "https://www.youtube.com/watch?v=hFP3qh1x1Zo", SongTwoURL: "https://www.youtube.com/watch?v=H6bjwDFk8mo", SongThreeURL: "https://www.youtube.com/watch?v=ZqtvrsNLFMs", SongFourURL: "https://www.youtube.com/watch?v=bOWWLytfmnU", SongFiveURL: "https://www.youtube.com/watch?v=hL8B98PuszY", SongOneName: "Worry", SongTwoName: "Wheatherd", SongThreeName: "Breathe Life", SongFourName: "The Love You're Given", SongFiveName: "Remnants", Day: "Day 3"))
        arrayOfAllBands.append(DetailBandClass(Name: "Jackal", Genre: "Rock", SongOneURL: "https://www.youtube.com/watch?v=mC-Zq0AIkiI", SongTwoURL: "https://www.youtube.com/watch?v=mC-Zq0AIkiI", SongThreeURL: "https://www.youtube.com/watch?v=m6z5mo4VQ5M", SongFourURL: "https://www.youtube.com/watch?v=VLbNCvcMpIE", SongFiveURL: "https://www.youtube.com/watch?v=SduvoFSgWeY", SongOneName: "ShakeDown", SongTwoName: "Let Me Tell you Something", SongThreeName: "Carbomb", SongFourName: "Netflix N Kill", SongFiveName: "Sunny Side Of The Day", Day: "Day 4"))
        arrayOfAllBands.append(DetailBandClass(Name: "Janes Addiction", Genre: "Rock", SongOneURL: "https://www.youtube.com/watch?v=anWmfN-dODs", SongTwoURL: "https://www.youtube.com/watch?v=jrwjiO1MCVs", SongThreeURL: "https://www.youtube.com/watch?v=1kAIMlISHhU", SongFourURL: "https://www.youtube.com/watch?v=sb3FJdRk-tI", SongFiveURL: "https://www.youtube.com/watch?v=V9ROmxvSYr4", SongOneName: "Jane Says ", SongTwoName: "Been Caught Stealing", SongThreeName: "Mountain Song ", SongFourName: "Just Because", SongFiveName: "Sympathy", Day: "Day 3"))
        arrayOfAllBands.append(DetailBandClass(Name: "Jarryd James", Genre: "Alternative", SongOneURL: "https://www.youtube.com/watch?v=QQ7XJG0Z2ho", SongTwoURL: "https://www.youtube.com/watch?v=f43T6OuM3hI", SongThreeURL: "https://www.youtube.com/watch?v=U5mHGbjsqUc", SongFourURL: "https://www.youtube.com/watch?v=EVgyiuFYKXc", SongFiveURL: "https://www.youtube.com/watch?v=U0l_GIvv_oY", SongOneName: "Do You Remeber", SongTwoName: "Give Me Something", SongThreeName: "Regardless", SongFourName: "This Time", SongFiveName: "Sure Love", Day: "Day 3"))
        arrayOfAllBands.append(DetailBandClass(Name: "Jauz", Genre: "Electronic", SongOneURL: "https://www.youtube.com/watch?v=jHyvlBDv3CI", SongTwoURL: "https://www.youtube.com/watch?v=jHyvlBDv3CI", SongThreeURL: "https://www.youtube.com/watch?v=p2cDjhA8sP4", SongFourURL: "https://www.youtube.com/watch?v=hkYq02183fc", SongFiveURL: "https://www.youtube.com/watch?v=HkYjFCZrM68", SongOneName: "Sqaud Out", SongTwoName: "Get On Up", SongThreeName: "Deeper Love", SongFourName: "Feel The Volume", SongFiveName: "Rock The Party (Radio Edit)", Day: "Day 3"))
        arrayOfAllBands.append(DetailBandClass(Name: "Jazz Cartier", Genre: "Rap", SongOneURL: "", SongTwoURL: "", SongThreeURL: "", SongFourURL: "", SongFiveURL: "", SongOneName: "", SongTwoName: "", SongThreeName: "", SongFourName: "", SongFiveName: "", Day: ""))
        //K
        arrayOfAllBands.append(DetailBandClass(Name: "Hehlani", Genre: "Hip Hop", SongOneURL: "https://www.youtube.com/watch?v=0E1xYcXsGp0", SongTwoURL: "https://www.youtube.com/watch?v=gxHK6Irgt1Q", SongThreeURL: "https://www.youtube.com/watch?v=9YwJiVRlR3c", SongFourURL: "https://www.youtube.com/watch?v=x3c61jEMu_4", SongFiveURL: "https://www.youtube.com/watch?v=FY0DCUSMfZc", SongOneName: "The Way", SongTwoName: "FWU", SongThreeName: "You Should Be Here", SongFourName: "Did I ", SongFiveName: "Down for You ", Day: "Day 1"))
        arrayOfAllBands.append(DetailBandClass(Name: "Kiiara", Genre: "Pop", SongOneURL: "https://www.youtube.com/watch?v=F1pB4rCz3dQ", SongTwoURL: "https://www.youtube.com/watch?v=rTlqY9i7Gn4", SongThreeURL: "https://www.youtube.com/watch?v=snZtuWcazfw", SongFourURL: "https://www.youtube.com/watch?v=K6RjrKDjJzI", SongFiveURL: "https://www.youtube.com/watch?v=bL3emtAXMv0", SongOneName: "Gold", SongTwoName: "Feels", SongThreeName: "Intention", SongFourName: "Tennessee", SongFiveName: "Say Any More", Day: "Day 1 "))
        arrayOfAllBands.append(DetailBandClass(Name: "Kurt Vile", Genre: "Rock", SongOneURL: "https://www.youtube.com/watch?v=659pppwniXA", SongTwoURL: "https://www.youtube.com/watch?v=KSh5ZJd7DnE", SongThreeURL: "", SongFourURL: "https://www.youtube.com/watch?v=J0p3AiVkWzU", SongFiveURL: "https://www.youtube.com/watch?v=63KB-EJKdyI", SongOneName: "Pretty Pimpin", SongTwoName: "Wakin On a Pretty Day", SongThreeName: "B’lieve I’m Goin Down", SongFourName: "Life Like This", SongFiveName: "Baby’s Arms", Day: "Day 1"))
        //L
        arrayOfAllBands.append(DetailBandClass(Name: "Lana Del Rey", Genre: "Alternative", SongOneURL: "https://www.youtube.com/watch?v=nVjsGKrE6E8", SongTwoURL: "https://www.youtube.com/watch?v=o_1aF54DO60", SongThreeURL: "https://www.youtube.com/watch?v=Bag1gUxuU0g", SongFourURL: "https://www.youtube.com/watch?v=QnxpHIl5Ynw", SongFiveURL: "https://www.youtube.com/watch?v=cE6wxDqdOV0", SongOneName: "Summer Time Sdaness", SongTwoName: "Born To Die", SongThreeName: "Young And Beautiful", SongFourName: "Video Games", SongFiveName: "Ride", Day: "Day 1"))
        arrayOfAllBands.append(DetailBandClass(Name: "Lapsley", Genre: "Electronic", SongOneURL: "https://www.youtube.com/watch?v=Kn5LXZv11ww", SongTwoURL: "https://www.youtube.com/watch?v=wXmaDGAlLvU", SongThreeURL: "https://www.youtube.com/watch?v=Pisxp5Gi3co", SongFourURL: "https://www.youtube.com/watch?v=uD7_Vt5q2q8", SongFiveURL: "https://www.youtube.com/watch?v=HyMfMYRpHUg", SongOneName: "Hurt Me ", SongTwoName: "Love Is Blind", SongThreeName: "Falling Short", SongFourName: "Station", SongFiveName: "Painter", Day: "Day 4 "))
        arrayOfAllBands.append(DetailBandClass(Name: "LazyBoy Empire", Genre: "", SongOneURL: "", SongTwoURL: "", SongThreeURL: "", SongFourURL: "", SongFiveURL: "", SongOneName: "", SongTwoName: "", SongThreeName: "", SongFourName: "", SongFiveName: "", Day: ""))
        arrayOfAllBands.append(DetailBandClass(Name: "LCD SoundSystem", Genre: "Rock", SongOneURL: "https://www.youtube.com/watch?v=OoA0cTC228M", SongTwoURL: "https://www.youtube.com/watch?v=Cj8JrQ9w5jY", SongThreeURL: "https://www.youtube.com/watch?v=-eohHwsplvY", SongFourURL: "https://www.youtube.com/watch?v=6xG4oFny2Pk", SongFiveURL: "https://www.youtube.com/watch?v=9L8yEDcZ-QI", SongOneName: "Dance Yrself Clean", SongTwoName: "Daft Punk Is Playing At My House", SongThreeName: "New York, I Love You But You’re...", SongFourName: "Losing MyEdge", SongFiveName: "All My Friends", Day: "Day 4"))
        arrayOfAllBands.append(DetailBandClass(Name: "Leon Bridges", Genre: "Alternative", SongOneURL: "https://www.youtube.com/watch?v=MTrKkqE9p1o", SongTwoURL: "https://www.youtube.com/watch?v=HYplnRjMVhM", SongThreeURL: "https://www.youtube.com/watch?v=jPdzSFEVQss", SongFourURL: "https://www.youtube.com/watch?v=0Hegd4xNfRo", SongFiveURL: "https://www.youtube.com/watch?v=pgS_xob1x4A", SongOneName: "Coming Home", SongTwoName: "Smooth Sailin” ", SongThreeName: "Lisa Sawyer", SongFourName: "River", SongFiveName: "Better Men", Day: "Day 3"))
        arrayOfAllBands.append(DetailBandClass(Name: "Lettuce", Genre: "Pop", SongOneURL: "https://www.youtube.com/watch?v=Xy_eAqPgC3o", SongTwoURL: "https://www.youtube.com/watch?v=Tyt_4N4LNz4", SongThreeURL: "https://www.youtube.com/watch?v=Y3ohZjCKzjg", SongFourURL: "https://www.youtube.com/watch?v=FPG9ax85sIo", SongFiveURL: "https://www.youtube.com/watch?v=95XAyPL_bt4", SongOneName: "Brain Reaction", SongTwoName: "Do it Like You Do", SongThreeName: "Lettsanity", SongFourName: "Fly", SongFiveName: "Ziggowatt", Day: "Day 2"))
        arrayOfAllBands.append(DetailBandClass(Name: "Lewis Del Mar", Genre: "Rock", SongOneURL: "https://www.youtube.com/watch?v=vVFwuq44UTQ", SongTwoURL: "https://www.youtube.com/watch?v=XGrpK-sQD3E", SongThreeURL: "https://www.youtube.com/watch?v=_63uM8Vl4sg", SongFourURL: "https://www.youtube.com/watch?v=q0hx0VdU60U", SongFiveURL: "", SongOneName: "Loud", SongTwoName: "Wave", SongThreeName: "Malt Liquor ", SongFourName: "Memories", SongFiveName: "", Day: "Day 2"))
        arrayOfAllBands.append(DetailBandClass(Name: "Lindsey Sirling", Genre: "Electronic", SongOneURL: "https://www.youtube.com/watch?v=aHjpOzsQ9YI", SongTwoURL: "https://www.youtube.com/watch?v=49tpIMDy9BE", SongThreeURL: "https://www.youtube.com/watch?v=jvipPYFebWc", SongFourURL: "https://www.youtube.com/watch?v=aE2GCa-_nyU", SongFiveURL: "https://www.youtube.com/watch?v=sf6LD2B_kDQ", SongOneName: "Crysatallize", SongTwoName: "Shader Me", SongThreeName: "Round Table Rival", SongFourName: "Radioactive", SongFiveName: "Elements", Day: "Day 4"))

        
        




    }
    func tableView(tableView: UITableView, cellForRowAtIndexPath indexPath: NSIndexPath) -> UITableViewCell
    {
        let myTableViewCell = allBandsTableView.dequeueReusableCellWithIdentifier("myCell", forIndexPath: indexPath)
        myTableViewCell.textLabel?.text = arrayOfAllBands[indexPath.row].name
        return myTableViewCell

        
    }
    func tableView(tableView: UITableView, numberOfRowsInSection section: Int) -> Int
    {
        return arrayOfAllBands.count
//        return section; 0 == 3
        //return 1
    }
    
    override func prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?)
    {
        let detailVC = segue.destinationViewController as! SongsBySelectedBand
        let selectedRow = allBandsTableView.indexPathForSelectedRow?.row
        detailVC.band = arrayOfAllBands[selectedRow!] //detailVC.superhero(reciever) = superheros[selectedRow](quarterback)
    }
    //////////////////////////////////////////////////////////////////
////    func numberOfSectionsInTableView(tableView: UITableView) -> Int
////    {
////        return arrayOfLetters.count
////    }
//    
//    func sectionIndexTitlesForTableView(tableView: UITableView) -> [String]?
//    {
//        return arrayOfLetters
//    }
//    
//    func tableView(tableView: UITableView, sectionForSectionIndexTitle title: String, atIndex index: Int) -> Int
//    {
//        let temp = arrayOfLetters as NSArray
//        return temp.indexOfObject(title)
//    }
//    
//    func tableView(tableView: UITableView, titleForHeaderInSection section: Int) -> String?
//    {
//        return arrayOfLetters[section]
//    }
//    func numberOfSectionsInTableView(tableView: UITableView) -> Int
//    {
//        return arrayOfLetters.count
//    }
    ////////////////////////////
    
    //if arrayOfAllBands.day = "Day 1"
    //{
    
    //}
    
//    func tableView(tableView: UITableView, sectionForSectionIndexTitle title: String, atIndex index: Int) -> Int
//    {
//        return arrayOfLetters
//    }

}

























