//
//  BandsInSelectedDay.swift
//  Lolla Lineup
//
//  Created by jcysewski on 4/7/16.
//  Copyright © 2016 jcysewski. All rights reserved.
//

import UIKit

class BandsInSelectedDay: UIViewController,  UITableViewDataSource, UITableViewDelegate
{
    @IBOutlet weak var bandsInSelectedDayTableView: UITableView!
    
    var arrayOfAllBands: [DetailBandClass] = []
    
    var day : [DetailBandClass!] = []
    var title1 = ""
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        navigationItem.title = title1
        bandsInSelectedDayTableView.dataSource = self
        bandsInSelectedDayTableView.delegate = self
        
        
        if title1 == "Day 1"
        {
            arrayOfAllBands.append(DetailBandClass(Name: "Alle Farben", Genre: "Pop", SongOneURL: "https://www.youtube.com/watch?v=HC1MmjPu3Xo", SongTwoURL: "https://www.youtube.com/watch?v=okBwFEz0TRI", SongThreeURL: "https://www.youtube.com/watch?v=zQAr3__aSn0", SongFourURL: "https://www.youtube.com/watch?v=V1Al3wMiEek", SongFiveURL: "https://www.youtube.com/watch?v=jGQWafRX7IE", SongOneName: "She Moves", SongTwoName: "Sometimes", SongThreeName: "She Moves - Acoustic Guitar Version", SongFourName: "Get High", SongFiveName: "Danse (Drauf & Dran Remix)", Day: "Day 1"))
            arrayOfAllBands.append(DetailBandClass(Name: "Alunageorge", Genre: "Electronic", SongOneURL: "https://www.youtube.com/watch?v=VfCSx5641U4", SongTwoURL: "https://www.youtube.com/watch?v=aBn7bjy9c4U", SongThreeURL: "https://www.youtube.com/watch?v=7d_HD89ZlJE", SongFourURL: "https://www.youtube.com/watch?v=wecvxQElEU0", SongFiveURL: "https://www.youtube.com/watch?v=gfVfXCSYWd0", SongOneName: "Your Drums, Your Love", SongTwoName: "You Know You Like It", SongThreeName: "Attracting Flies", SongFourName: "Supernatural", SongFiveName: "Outlines", Day: "Day 1"))
            arrayOfAllBands.append(DetailBandClass(Name: "Auto Lux", Genre: "Alternative", SongOneURL: "https://www.youtube.com/watch?v=uZL91Uv5e8g", SongTwoURL: "https://www.youtube.com/watch?v=AogGLXkUuvQ", SongThreeURL: "https://www.youtube.com/watch?v=0uGt1n3xERo", SongFourURL: "https://www.youtube.com/watch?v=SD67M_ZpJYk", SongFiveURL: "https://www.youtube.com/watch?v=c1GfAfcgUw4", SongOneName: "Turnstile Blues", SongTwoName: "Angry Candy", SongThreeName: "Sugarless", SongFourName: "Subzero Fun", SongFiveName: "Here Comes Everybody", Day: "Day 1"))
            arrayOfAllBands.append(DetailBandClass(Name: "Bad Royale", Genre: "Electronic", SongOneURL: "https://www.youtube.com/watch?v=Q7gpn6wOTuo", SongTwoURL: "https://www.youtube.com/watch?v=KpU93h4wFSk", SongThreeURL: "https://www.youtube.com/watch?v=_9vdwJn6kPY", SongFourURL: "https://www.youtube.com/watch?v=FuwQkx21CsA", SongFiveURL: "https://www.youtube.com/watch?v=wcZyG_4AOeA", SongOneName: "King is Back feat. Big Ali - Bad Royale Remix", SongTwoName: "Pop (feat. Dominique Young Unique)", SongThreeName: "One Puff", SongFourName: "Move Like (feat. Richie Loop)", SongFiveName: "Bounce With Me (feat. Clinton Sky)", Day: "Day 1"))
            arrayOfAllBands.append(DetailBandClass(Name: "Bas", Genre: "Rap", SongOneURL: "https://www.youtube.com/watch?v=YyALkCHSh_0", SongTwoURL: "https://www.youtube.com/watch?v=sF--UJ3zEO4", SongThreeURL: "https://www.youtube.com/watch?v=70x4yfWpLb0", SongFourURL: "https://www.youtube.com/watch?v=E2xEfMyBtUg", SongFiveURL: "https://www.youtube.com/watch?v=WCWubSL5LeE", SongOneName: "House Wives", SongTwoName: "Aethalia", SongThreeName: "Night Job", SongFourName: "My Nigga Just Made Bail", SongFiveName: "Lit - Bonus", Day: "Day 1"))
            arrayOfAllBands.append(DetailBandClass(Name: "Bastille", Genre: "Rock", SongOneURL: "https://www.youtube.com/watch?v=F90Cw4l-8NY", SongTwoURL: "https://www.youtube.com/watch?v=MGR4U7W1dZU", SongThreeURL: "https://www.youtube.com/watch?v=1E36WU9Wzf4", SongFourURL: "https://www.youtube.com/watch?v=qoNYlV07Cf8", SongFiveURL: "https://www.youtube.com/watch?v=ZCTDKLjdok4", SongOneName: "Pompeii", SongTwoName: "Things We Lost in the Fire", SongThreeName: "Flaws", SongFourName: "Bad Blood", SongFiveName: "Of The Night", Day: "Day 1"))
            arrayOfAllBands.append(DetailBandClass(Name: "Bob Moses", Genre: "Electronic", SongOneURL: "https://www.youtube.com/watch?v=R9Fv4nW0KaM", SongTwoURL: "https://www.youtube.com/watch?v=NAS5Z1GvxrQ", SongThreeURL: "https://www.youtube.com/watch?v=33uyeDpMBlY", SongFourURL: "https://www.youtube.com/watch?v=MzKrszohZVY", SongFiveURL: "https://www.youtube.com/watch?v=hyAoQAzwX5g", SongOneName: "Too Much Is Never Enough", SongTwoName: "Tearing Me Up", SongThreeName: "All I Want", SongFourName: "I Ain’t Gonna Be The First To Cry", SongFiveName: "Grace", Day: "Day 1"))
            arrayOfAllBands.append(DetailBandClass(Name: "Cashmere Cat", Genre: "Electronic", SongOneURL: "https://www.youtube.com/watch?v=kxELjU3f7Z4", SongTwoURL: "https://www.youtube.com/watch?v=be-LbSaEzZQ", SongThreeURL: "https://www.youtube.com/watch?v=9RNQxY-YVKs", SongFourURL: "https://www.youtube.com/watch?v=MdoB_kYLTGw", SongFiveURL: "https://www.youtube.com/watch?v=lDWIPCTime4", SongOneName: "Mirror Maru", SongTwoName: "With Me", SongThreeName: "Kiss Kiss", SongFourName: "Adore", SongFiveName: "Paws", Day: "Day 1"))
            arrayOfAllBands.append(DetailBandClass(Name: "City and Colour", Genre: "Alternative", SongOneURL: "https://www.youtube.com/watch?v=mS8xDo-qM8w", SongTwoURL: "https://www.youtube.com/watch?v=NjMsWarn8BI", SongThreeURL: "https://www.youtube.com/watch?v=8rU7WPVcLmQ", SongFourURL: "https://www.youtube.com/watch?v=SBsRyktvXf0", SongFiveURL: "https://www.youtube.com/watch?v=NZIj31QHidY", SongOneName: "The Girl", SongTwoName: "Comin Home", SongThreeName: "Sleeping Sickness", SongFourName: "Hello, I’m In Delaware", SongFiveName: "Save Your Scissors", Day: "Day 1"))
            arrayOfAllBands.append(DetailBandClass(Name: "Cloves", Genre: "Rock", SongOneURL: "https://www.youtube.com/watch?v=1FGrjh8j8z0", SongTwoURL: "https://www.youtube.com/watch?v=F5UAvgr_Ipg", SongThreeURL: "https://www.youtube.com/watch?v=F_Jk_uQ4gSg", SongFourURL: "https://www.youtube.com/watch?v=0S7E7hczBiA", SongFiveURL: "", SongOneName: "Frail Love", SongTwoName: "Everybody’s Son", SongThreeName: "Don’t You Wait", SongFourName: "Don’t Forget About Me", SongFiveName: "", Day: "Day 1"))
            arrayOfAllBands.append(DetailBandClass(Name: "Cozz", Genre: "Rap", SongOneURL: "https://www.youtube.com/watch?v=Y7d42LJfkqQ", SongTwoURL: "https://www.youtube.com/watch?v=i8Dg6qj8L3M", SongThreeURL: "https://www.youtube.com/watch?v=6FdKK6qO6sA", SongFourURL: "https://www.youtube.com/watch?v=ObQeKIJhFuI", SongFiveURL: "https://www.youtube.com/watch?v=K4wUiGFwDPM", SongOneName: "Knock Tha Hustle - Remix", SongTwoName: "Dreams", SongThreeName: "Im Tha Man", SongFourName: "Cody Macc", SongFiveName: "Come Get It", Day: "Day 1"))
            arrayOfAllBands.append(DetailBandClass(Name: "Danny Brown", Genre: "Hip Hop", SongOneURL: "https://www.youtube.com/watch?v=hCdgDxQbW_U", SongTwoURL: "https://www.youtube.com/watch?v=7cxC4UeZbHk", SongThreeURL: "https://www.youtube.com/watch?v=pcGGfojS58U", SongFourURL: "https://vimeo.com/91583133", SongFiveURL: "https://www.youtube.com/watch?v=NHfWY0is3rE", SongOneName: "Detroit vs Everybody", SongTwoName: "Side B", SongThreeName: "Kush Coma", SongFourName: "25 Bucks", SongFiveName: "Grown Up", Day: "Day 1"))
            arrayOfAllBands.append(DetailBandClass(Name: "Daughter", Genre: "Rock", SongOneURL: "https://www.youtube.com/watch?v=2QT5eGHCJdE", SongTwoURL: "https://www.youtube.com/watch?v=90mzH1kvznQ", SongThreeURL: "https://www.youtube.com/watch?v=aM2lObw1CbY", SongFourURL: "https://www.youtube.com/watch?v=uUWrcFpmI5U", SongFiveURL: "https://www.youtube.com/watch?v=GnkzvAXWV-0", SongOneName: "Youth", SongTwoName: "Candles", SongThreeName: "Medicine", SongFourName: "Still", SongFiveName: "Smother", Day: "Day 1"))
            arrayOfAllBands.append(DetailBandClass(Name: "Don Diablo", Genre: "House", SongOneURL: "https://www.youtube.com/watch?v=Cbvqv19Nf0E", SongTwoURL: "https://www.youtube.com/watch?v=r6E3J4GPpjc", SongThreeURL: "https://www.youtube.com/watch?v=hVB3LNDE6pE", SongFourURL: "https://www.youtube.com/watch?v=RJOmSMQVCXg", SongFiveURL: "https://www.youtube.com/watch?v=Ue8PpA557Bc", SongOneName: "Chemicals", SongTwoName: "On My Mind", SongThreeName: "Universe", SongFourName: "Starlight", SongFiveName: "Knight Time", Day: "Day 1"))
            arrayOfAllBands.append(DetailBandClass(Name: "Excision", Genre: "Electronic", SongOneURL: "https://www.youtube.com/watch?v=8dZDdW7v4Q8", SongTwoURL: "https://www.youtube.com/watch?v=3-UAKEJDOXw", SongThreeURL: "https://www.youtube.com/watch?v=g_8cjKU2ve8", SongFourURL: "https://www.youtube.com/watch?v=3pDKFLEvd3o", SongFiveURL: "https://www.youtube.com/watch?v=fphS3QKh2ZQ", SongOneName: "Bring The Madness", SongTwoName: "Robo Kitty", SongThreeName: "CodeName X", SongFourName: "X Rated", SongFiveName: "Swagga", Day: "Day 1"))
            arrayOfAllBands.append(DetailBandClass(Name: "Flosstrdamus", Genre: "Hip Hop", SongOneURL: "https://www.youtube.com/watch?v=LgiyMpKBl28", SongTwoURL: "https://www.youtube.com/watch?v=YUbsKY8JCvw", SongThreeURL: "https://www.youtube.com/watch?v=OcvunrplrZc", SongFourURL: "https://www.youtube.com/watch?v=imHTgWXmR7g", SongFiveURL: "https://www.youtube.com/watch?v=KNByf1o4T_8", SongOneName: "SoundClash", SongTwoName: "Drop Top", SongThreeName: "Prison Riot", SongFourName: "TTU", SongFiveName: "Mosh Pit", Day: "Day 1"))
            arrayOfAllBands.append(DetailBandClass(Name: "Frances", Genre: "Pop", SongOneURL: "https://www.youtube.com/watch?v=bzWkKXuv00U", SongTwoURL: "https://www.youtube.com/watch?v=zDuphKT2mFg", SongThreeURL: "https://www.youtube.com/watch?v=_Hw3h9cAIFk", SongFourURL: "https://www.youtube.com/watch?v=O5X5ZUvq5XY", SongFiveURL: "https://www.youtube.com/watch?v=sS0rKUnW0k8", SongOneName: "Don’t Worry About Me", SongTwoName: "Set Sail", SongThreeName: "Borrowed Time", SongFourName: "Let It Out", SongFiveName: "Grow", Day: "Day 1"))
            arrayOfAllBands.append(DetailBandClass(Name: "G Eazy", Genre: "Rap", SongOneURL: "https://www.youtube.com/watch?v=bSfpSOBD30U", SongTwoURL: "https://www.youtube.com/watch?v=CxnaPa8ohmM", SongThreeURL: "https://www.youtube.com/watch?v=fu7NR1qe_Mk", SongFourURL: "https://www.youtube.com/watch?v=UI9WCl4Cd8E", SongFiveURL: "https://www.youtube.com/watch?v=-3wlroM2gZ8", SongOneName: "Me Myself & I", SongTwoName: "I Mean It", SongThreeName: "Tumblr Girls", SongFourName: "Order More", SongFiveName: "You Got Me", Day: "Day 1"))
            arrayOfAllBands.append(DetailBandClass(Name: "Grand Theft ", Genre: "Hip Hop", SongOneURL: "https://www.youtube.com/watch?v=8T7_1nPQoS0", SongTwoURL: "https://www.youtube.com/watch?v=bTkTl8vk6Cc", SongThreeURL: "https://www.youtube.com/watch?v=wq94Jp8MJgI", SongFourURL: "https://www.youtube.com/watch?v=JRWtHcZkJMc", SongFiveURL: "https://www.youtube.com/watch?v=xD5S4BpBPcw", SongOneName: "Keep It 100", SongTwoName: "Mobbin", SongThreeName: "Quit This City", SongFourName: "Let Me Tell You Something", SongFiveName: "All The Way Up", Day: "Day 1"))
            arrayOfAllBands.append(DetailBandClass(Name: "Hiatus Kaiyote", Genre: "Electronic", SongOneURL: "https://www.youtube.com/watch?v=Ozr4KsZBTvQ", SongTwoURL: "https://www.youtube.com/watch?v=9ZVMViSx6Ek", SongThreeURL: "https://www.youtube.com/watch?v=2L-UbZJSfW8", SongFourURL: "https://www.youtube.com/watch?v=-Ilr1AY41AA", SongFiveURL: "https://www.youtube.com/watch?v=ya7aDtEdTTo", SongOneName: "Nakamarra", SongTwoName: "Breathing Under Water", SongThreeName: "Lace Skull", SongFourName: "By Fire", SongFiveName: "Shaolin Monk MotherFunk", Day: "Day 1"))
            arrayOfAllBands.append(DetailBandClass(Name: "J.Cole", Genre: "Hip Hop", SongOneURL: "https://www.youtube.com/watch?v=y-vQ_VsTkn0", SongTwoURL: "https://www.youtube.com/watch?v=N6PyB9Feu_k", SongThreeURL: "https://www.youtube.com/watch?v=9VzpCmRtCL0", SongFourURL: "https://www.youtube.com/watch?v=-BmKepFmBQs", SongFiveURL: "https://www.youtube.com/watch?v=-dyPeGDeS3o", SongOneName: "Lost Ones", SongTwoName: "Simba", SongThreeName: "Be Free", SongFourName: "I Get Up", SongFiveName: "Lights Please", Day: "Day 1"))
            arrayOfAllBands.append(DetailBandClass(Name: "Jazz Cartier", Genre: "Rap", SongOneURL: "https://www.youtube.com/watch?v=FH_QApWnu-A", SongTwoURL: "https://www.youtube.com/watch?v=TVynVTXoK3o", SongThreeURL: "https://www.youtube.com/watch?v=C6McIu7kfZU", SongFourURL: "https://www.youtube.com/watch?v=7pmOwlUVNKY", SongFiveURL: "https://www.youtube.com/watch?v=hzxQvfpmebA", SongOneName: "Switch", SongTwoName: "The Valley", SongThreeName: "Opera", SongFourName: "Dead Or Alive", SongFiveName: "New Religion", Day: "Day 1"))
            arrayOfAllBands.append(DetailBandClass(Name: "Kehlani", Genre: "Hip Hop", SongOneURL: "https://www.youtube.com/watch?v=0E1xYcXsGp0", SongTwoURL: "https://www.youtube.com/watch?v=gxHK6Irgt1Q", SongThreeURL: "https://www.youtube.com/watch?v=9YwJiVRlR3c", SongFourURL: "https://www.youtube.com/watch?v=x3c61jEMu_4", SongFiveURL: "https://www.youtube.com/watch?v=FY0DCUSMfZc", SongOneName: "The Way", SongTwoName: "FWU", SongThreeName: "You Should Be Here", SongFourName: "Did I ", SongFiveName: "Down for You ", Day: "Day 1"))
            arrayOfAllBands.append(DetailBandClass(Name: "Kiiara", Genre: "Pop", SongOneURL: "https://www.youtube.com/watch?v=F1pB4rCz3dQ", SongTwoURL: "https://www.youtube.com/watch?v=rTlqY9i7Gn4", SongThreeURL: "https://www.youtube.com/watch?v=snZtuWcazfw", SongFourURL: "https://www.youtube.com/watch?v=K6RjrKDjJzI", SongFiveURL: "https://www.youtube.com/watch?v=bL3emtAXMv0", SongOneName: "Gold", SongTwoName: "Feels", SongThreeName: "Intention", SongFourName: "Tennessee", SongFiveName: "Say Any More", Day: "Day 1 "))
            arrayOfAllBands.append(DetailBandClass(Name: "Kurt Vile", Genre: "Rock", SongOneURL: "https://www.youtube.com/watch?v=659pppwniXA", SongTwoURL: "https://www.youtube.com/watch?v=KSh5ZJd7DnE", SongThreeURL: "", SongFourURL: "https://www.youtube.com/watch?v=J0p3AiVkWzU", SongFiveURL: "https://www.youtube.com/watch?v=63KB-EJKdyI", SongOneName: "Pretty Pimpin", SongTwoName: "Wakin On a Pretty Day", SongThreeName: "B’lieve I’m Goin Down", SongFourName: "Life Like This", SongFiveName: "Baby’s Arms", Day: "Day 1"))
            arrayOfAllBands.append(DetailBandClass(Name: "Lana Del Rey", Genre: "Alternative", SongOneURL: "https://www.youtube.com/watch?v=nVjsGKrE6E8", SongTwoURL: "https://www.youtube.com/watch?v=o_1aF54DO60", SongThreeURL: "https://www.youtube.com/watch?v=Bag1gUxuU0g", SongFourURL: "https://www.youtube.com/watch?v=QnxpHIl5Ynw", SongFiveURL: "https://www.youtube.com/watch?v=cE6wxDqdOV0", SongOneName: "Summer Time Sdaness", SongTwoName: "Born To Die", SongThreeName: "Young And Beautiful", SongFourName: "Video Games", SongFiveName: "Ride", Day: "Day 1"))
            arrayOfAllBands.append(DetailBandClass(Name: "Melanie Martinez", Genre: "Electronic", SongOneURL: "https://www.youtube.com/watch?v=HcVv9R1ZR84", SongTwoURL: "https://www.youtube.com/watch?v=6bAPlojfgO0", SongThreeURL: "https://www.youtube.com/watch?v=O87lzhoexyA", SongFourURL: "https://www.youtube.com/watch?v=6GtPW4nB3Ro", SongFiveURL: "https://www.youtube.com/watch?v=VdwaWp59qz8", SongOneName: "Doll House", SongTwoName: "Pity Party", SongThreeName: "Cry Baby", SongFourName: "Mad Hatter", SongFiveName: "Sippy Cup", Day: "Day 1"))
            arrayOfAllBands.append(DetailBandClass(Name: "Melanie Martinez", Genre: "Electronic", SongOneURL: "https://www.youtube.com/watch?v=HcVv9R1ZR84", SongTwoURL: "https://www.youtube.com/watch?v=6bAPlojfgO0", SongThreeURL: "https://www.youtube.com/watch?v=O87lzhoexyA", SongFourURL: "https://www.youtube.com/watch?v=6GtPW4nB3Ro", SongFiveURL: "https://www.youtube.com/watch?v=VdwaWp59qz8", SongOneName: "Doll House", SongTwoName: "Pity Party", SongThreeName: "Cry Baby", SongFourName: "Mad Hatter", SongFiveName: "Sippy Cup", Day: "Day 1"))
            arrayOfAllBands.append(DetailBandClass(Name: "Mr. Carmack", Genre: "Electronic", SongOneURL: "https://www.youtube.com/watch?v=HHmHLx9x5Os", SongTwoURL: "https://www.youtube.com/watch?v=_K-TQR18ZfI", SongThreeURL: "https://www.youtube.com/watch?v=-QyPLMLvnfw", SongFourURL: "https://www.youtube.com/watch?v=g6Vuu3J8toI", SongFiveURL: "https://www.youtube.com/watch?v=D3Nx8C7vDz4", SongOneName: "Uppers", SongTwoName: "Muney", SongThreeName: "Pay", SongFourName: "Let Me Go", SongFiveName: "Humbled", Day: "Day 1"))
            arrayOfAllBands.append(DetailBandClass(Name: "Omen", Genre: "Hip Hop", SongOneURL: "https://www.youtube.com/watch?v=Dy0hL_RxOAQ", SongTwoURL: "https://www.youtube.com/watch?v=JSebL5ouJh0", SongThreeURL: "https://www.youtube.com/watch?v=_sBwBN5gUzE", SongFourURL: "https://www.youtube.com/watch?v=GojGR6PTfVU", SongFiveURL: "https://www.youtube.com/watch?v=c18ofpFiS0A", SongOneName: "Things Change", SongTwoName: "Sweat It Out ", SongThreeName: "LoveDrug", SongFourName: "Big Shadows", SongFiveName: "Stretches Of Paranoia", Day: "Day 1"))
            arrayOfAllBands.append(DetailBandClass(Name: "Pine Grove", Genre: "Rock", SongOneURL: "https://www.youtube.com/watch?v=tkb26vFEp94", SongTwoURL: "https://www.youtube.com/watch?v=oBH2Mdvl9ik", SongThreeURL: "https://www.youtube.com/watch?v=kcf8lzF12fg", SongFourURL: "https://www.youtube.com/watch?v=AbFGMw1mY48", SongFiveURL: "https://www.youtube.com/watch?v=z37NMpqdiu0", SongOneName: "Old Friends", SongTwoName: "Alphasia", SongThreeName: "Size Of The Moon", SongFourName: "Cadmium", SongFiveName: "New Friends", Day: "Day 1"))
            arrayOfAllBands.append(DetailBandClass(Name: "SoMo", Genre: "Hip Hop ", SongOneURL: "https://www.youtube.com/watch?v=5082NM1H-io", SongTwoURL: "https://www.youtube.com/watch?v=1xloPa44uzA", SongThreeURL: "https://www.youtube.com/watch?v=5Ws9202qLao", SongFourURL: "https://www.youtube.com/watch?v=P_rpDHvAt88", SongFiveURL: "https://www.youtube.com/watch?v=o3-XLCv2WtQ", SongOneName: "Ride", SongTwoName: "We Can Make Love", SongThreeName: "Back To The Start", SongFourName: "Show Off", SongFiveName: "Hide & Freak", Day: "Day 1"))
            arrayOfAllBands.append(DetailBandClass(Name: "Tchami", Genre: "House", SongOneURL: "https://www.youtube.com/watch?v=iPioLizQKuc", SongTwoURL: "https://www.youtube.com/watch?v=EFS3T321VUY", SongThreeURL: "https://www.youtube.com/watch?v=DPHsToh4z3Y", SongFourURL: "https://www.youtube.com/watch?v=IvQXvgDfu_c", SongFiveURL: "https://www.youtube.com/watch?v=Fc8YoeAl-m8", SongOneName: "Promisses", SongTwoName: "After LIfe", SongThreeName: "Untrue", SongFourName: "Shot Caller", SongFiveName: "Missing You", Day: "Day 1 "))
            arrayOfAllBands.append(DetailBandClass(Name: "Tennyson", Genre: "Electronic", SongOneURL: "https://www.youtube.com/watch?v=VEETvq22Bsw", SongTwoURL: "https://www.youtube.com/watch?v=k9LpwtWkiAc", SongThreeURL: "https://www.youtube.com/watch?v=0Za_Qd37OGg", SongFourURL: "https://www.youtube.com/watch?v=QfThkU_aVF8", SongFiveURL: "https://www.youtube.com/watch?v=neUrR4txw6k", SongOneName: "You’re Cute", SongTwoName: "Lay-by", SongThreeName: "Ll'oiseau qui danse", SongFourName: "SLIPPERZ", SongFiveName: "Violet Alturas", Day: "Day 1"))
            arrayOfAllBands.append(DetailBandClass(Name: "The 1975", Genre: "Alternative", SongOneURL: "https://www.youtube.com/watch?v=xeDGfk0UJw8", SongTwoURL: "https://www.youtube.com/watch?v=FSnAllHtG70", SongThreeURL: "https://www.youtube.com/watch?v=TJ5bZuUlftI", SongFourURL: "https://www.youtube.com/watch?v=BsYE078RQCI", SongFiveURL: "https://www.youtube.com/watch?v=Iyy3YOpxL2k", SongOneName: "Chocolate", SongTwoName: "The Sound", SongThreeName: "Love Me", SongFourName: "Settle Down", SongFiveName: "Robbers", Day: "Day 1"))
            arrayOfAllBands.append(DetailBandClass(Name: "The Arcs", Genre: "Rock", SongOneURL: "https://www.youtube.com/watch?v=3CyjGhVua_s", SongTwoURL: "https://www.youtube.com/watch?v=EHCO6CRTLT8", SongThreeURL: "https://www.youtube.com/watch?v=0kcewVcjtiE", SongFourURL: "https://www.youtube.com/watch?v=_LPlT-iZ72k", SongFiveURL: "https://www.youtube.com/watch?v=1-hJ803XoJw", SongOneName: "Put a Flower in Your Pocket", SongTwoName: "Stay in My Corner", SongThreeName: "Outta My Mind", SongFourName: "Velvet Ditch", SongFiveName: "Pistol Made of Bones", Day: "Day 1"))
            arrayOfAllBands.append(DetailBandClass(Name: "The Last Shadow Puppets", Genre: "Pop", SongOneURL: "https://www.youtube.com/watch?v=IamcaGta7hY", SongTwoURL: "https://www.youtube.com/watch?v=nKKDGX66jhw", SongThreeURL: "https://www.youtube.com/watch?v=XGV8xCkpXjE", SongFourURL: "https://www.youtube.com/watch?v=9cQloro92xA", SongFiveURL: "https://www.youtube.com/watch?v=_8YRx47oylM", SongOneName: "Everything You’ve Come to Expect", SongTwoName: "Miracle Aligner", SongThreeName: "The Age of Understatement", SongFourName: "My Mistakes Were Made For You", SongFiveName: "Standing Next to Me", Day: "Day 1"))
            arrayOfAllBands.append(DetailBandClass(Name: "The Noisy Freaks", Genre: "House", SongOneURL: "https://www.youtube.com/watch?v=Dmb6WisLf-M", SongTwoURL: "https://www.youtube.com/watch?v=iXVjFga-Wrg", SongThreeURL: "https://www.youtube.com/watch?v=EzDmxV99LMI", SongFourURL: "https://www.youtube.com/watch?v=EzDmxV99LMI", SongFiveURL: "https://www.youtube.com/watch?v=EzDmxV99LMI", SongOneName: "Freaks Orchestra", SongTwoName: "Cheer Song", SongThreeName: "Straight Life", SongFourName: "Love Robot", SongFiveName: "Funky Kids", Day: "Day 1"))
            arrayOfAllBands.append(DetailBandClass(Name: "Towkio", Genre: "Hip Hop", SongOneURL: "https://www.youtube.com/watch?v=Ml_UdvxQiNw", SongTwoURL: "https://www.youtube.com/watch?v=J10do4rsPv8", SongThreeURL: "https://www.youtube.com/watch?v=DKTnWcD1DcM", SongFourURL: "https://www.youtube.com/watch?v=OYUMtINEtjo", SongFiveURL: "https://www.youtube.com/watch?v=7D9bYIDkth0", SongOneName: "American Apperal Girls", SongTwoName: "Shit 2.0", SongThreeName: "Ready", SongFourName: "Abstract", SongFiveName: "Body Bags Freestyle", Day: "Day 1"))
            arrayOfAllBands.append(DetailBandClass(Name: "Wavves", Genre: "Rock", SongOneURL: "https://www.youtube.com/watch?v=gPdx7Il9DrM", SongTwoURL: "https://www.youtube.com/watch?v=3v0OZlSXXug", SongThreeURL: "https://www.youtube.com/watch?v=lG8HCFQa3OQ", SongFourURL: "https://www.youtube.com/watch?v=PRThbqqzJGg", SongFiveURL: "https://www.youtube.com/watch?v=agmKa_CON9k", SongOneName: "Way Too Much", SongTwoName: "Nine is God", SongThreeName: "Demon To Lean On", SongFourName: "My Head Hurts", SongFiveName: "Green Eyes", Day: "Day 1"))
            arrayOfAllBands.append(DetailBandClass(Name: "Wild Child", Genre: "Alternative", SongOneURL: "https://www.youtube.com/watch?v=87PZgweY-gY", SongTwoURL: "https://www.youtube.com/watch?v=7Sd4pv1Nb7A", SongThreeURL: "https://www.youtube.com/watch?v=NEabXpxrJDs", SongFourURL: "https://www.youtube.com/watch?v=vPtvqouhfos", SongFiveURL: "https://www.youtube.com/watch?v=Xppeta7eoYI", SongOneName: "Crazy Bird", SongTwoName: "Silly Things", SongThreeName: "The Runaround", SongFourName: "Rilo Talk", SongFiveName: "The Tale of You & Me", Day: "Day 1"))
            arrayOfAllBands.append(DetailBandClass(Name: "YeaSayer", Genre: "Rock", SongOneURL: "https://www.youtube.com/watch?v=yW4Fb5GTMFc", SongTwoURL: "https://www.youtube.com/watch?v=6m1O5i6oUTI", SongThreeURL: "https://www.youtube.com/watch?v=olzw8qi6Ptw", SongFourURL: "https://www.youtube.com/watch?v=PwUctgGIZJQ", SongFiveURL: "https://www.youtube.com/watch?v=QO1y1wJduCo", SongOneName: "Ambling Alp", SongTwoName: "O.N.E.", SongThreeName: "2080", SongFourName: "Sunrise", SongFiveName: "Madder Red", Day: "Day 1"))

        }
        if title1 == "Day 2"
        {
            arrayOfAllBands.append(DetailBandClass(Name: "Alessia Cara", Genre: "Pop", SongOneURL: "https://www.youtube.com/watch?v=UKp2CrfmVfw", SongTwoURL: "https://www.youtube.com/watch?v=De30ET0dQpQ", SongThreeURL: "https://www.youtube.com/watch?v=Em7vc8NWUNY", SongFourURL: "https://www.youtube.com/watch?v=qbIaPaB9LDk", SongFiveURL: "https://www.youtube.com/watch?v=4b2M5K7sbc0", SongOneName: "Here", SongTwoName: "Wild Things", SongThreeName: "Scars to Your Beautiful", SongFourName: "Seventeen", SongFiveName: "River of Tears", Day: "Day 2"))
            arrayOfAllBands.append(DetailBandClass(Name: "Asap Ferg", Genre: "Hip Hop", SongOneURL: "https://www.youtube.com/watch?v=iXZxipry6kE", SongTwoURL: "https://www.youtube.com/watch?v=WjlkvM7mz1U", SongThreeURL: "https://www.youtube.com/watch?v=jkHI1hGvWRY", SongFourURL: "https://www.youtube.com/watch?v=hKFRwLIGri4", SongFiveURL: "https://www.youtube.com/watch?v=E8hzJpeRLG0", SongOneName: "Shabba", SongTwoName: "Hood Pope", SongThreeName: "Work Remix", SongFourName: "Let It Go", SongFiveName: "Dump Dump", Day: "Day 2"))
            arrayOfAllBands.append(DetailBandClass(Name: "Audien", Genre: "Rock", SongOneURL: "https://www.youtube.com/watch?v=9A3z5hmWUoY", SongTwoURL: "https://www.youtube.com/watch?v=_sDbRhC7rm8", SongThreeURL: "https://www.youtube.com/watch?v=Xr2DYH0zcZo", SongFourURL: "https://www.youtube.com/watch?v=ys7FfXtz_aQ", SongFiveURL: "https://www.youtube.com/watch?v=UhZlO4IpEP8", SongOneName: "Leaving You - Radio Edit", SongTwoName: "Something Better", SongThreeName: "Circles - Original Mix", SongFourName: "Hindsight", SongFiveName: "Wayfarer", Day: "Day 2"))
            arrayOfAllBands.append(DetailBandClass(Name: "BoomBox Cartel", Genre: "House", SongOneURL: "https://www.youtube.com/watch?v=Mt0bFWfqsDg", SongTwoURL: "https://www.youtube.com/watch?v=2odMhhbs4AI", SongThreeURL: "https://www.youtube.com/watch?v=3hUTH1ON-rw", SongFourURL: "https://www.youtube.com/watch?v=HL3SA-gLu-k", SongFiveURL: "https://www.youtube.com/watch?v=IQq8l4JnefI", SongOneName: "B2U (feat. Ian Everson)", SongTwoName: "Jamba", SongThreeName: "Where’s My Money", SongFourName: "Spaceless", SongFiveName: "Hysteria (“WTF Is Festival Trap” Anthem)", Day: "Day 2"))
            arrayOfAllBands.append(DetailBandClass(Name: "Bro Safari", Genre: "House", SongOneURL: "https://www.youtube.com/watch?v=XxGmgmelZV0", SongTwoURL: "https://www.youtube.com/watch?v=8o3nZQU4evo", SongThreeURL: "https://www.youtube.com/watch?v=ugLvpJWWhCA", SongFourURL: "https://www.youtube.com/watch?v=twbEV6fBNo8", SongFiveURL: "https://www.youtube.com/watch?v=bu3c8w53jA4", SongOneName: "The Drop", SongTwoName: "That A$$", SongThreeName: "Scumbag", SongFourName: "Da Worm", SongFiveName: "The Clap (feat. ETC!ETC!)", Day: "Day 2"))
            arrayOfAllBands.append(DetailBandClass(Name: "Cherub", Genre: "Rock", SongOneURL: "https://www.youtube.com/watch?v=E45fogGN_Y8", SongTwoURL: "https://www.youtube.com/watch?v=JZB3LTNjTWc", SongThreeURL: "https://www.youtube.com/watch?v=RRLfQL_DEfM", SongFourURL: "https://www.youtube.com/watch?v=aoUfpBYg4Ac", SongFiveURL: "", SongOneName: "Doses And Mimosas", SongTwoName: "XOXO", SongThreeName: "Disco Inferno", SongFourName: "Sucker For Love", SongFiveName: "", Day: "Day 2"))
            arrayOfAllBands.append(DetailBandClass(Name: "Con Brio", Genre: "Hip Hop", SongOneURL: "https://www.youtube.com/watch?v=jo-Puo61N0w", SongTwoURL: "https://www.youtube.com/watch?v=4-MNi7jwphI", SongThreeURL: "https://www.youtube.com/watch?v=WyovgZY5Vls", SongFourURL: "https://www.youtube.com/watch?v=yWE0eXnHXWI", SongFiveURL: "https://www.youtube.com/watch?v=uy1_h5VPzUk", SongOneName: "Apple", SongTwoName: "Never Be The Same", SongThreeName: "Give It All", SongFourName: "Kiss The Sun", SongFiveName: "California Cowboy", Day: "Day 2"))
            arrayOfAllBands.append(DetailBandClass(Name: "Day Wave", Genre: "Rock", SongOneURL: "https://www.youtube.com/watch?v=QUVGWkRJ3Pc", SongTwoURL: "https://www.youtube.com/watch?v=vLGc0Uq5RpU", SongThreeURL: "https://www.youtube.com/watch?v=Oh1Q0283GN4", SongFourURL: "https://www.youtube.com/watch?v=83KDgjM6__c", SongFiveURL: "https://www.youtube.com/watch?v=dJRJAWBINdE", SongOneName: "Come Home Now", SongTwoName: "Total Zombies", SongThreeName: "We Try But We Don’t Fit In", SongFourName: "Dead Beat Girl", SongFiveName: "Hard To Read", Day: "Day 2"))
            arrayOfAllBands.append(DetailBandClass(Name: "Duke Dumont", Genre: "House", SongOneURL: "https://www.youtube.com/watch?v=KDxJlW6cxRk", SongTwoURL: "https://www.youtube.com/watch?v=FHCYHldJi_g", SongThreeURL: "https://www.youtube.com/watch?v=FnJIb4A-DuY", SongFourURL: "https://www.youtube.com/watch?v=6oAqOFz6QsU", SongFiveURL: "https://www.youtube.com/watch?v=kv_cwzAIOHs", SongOneName: "Ocean Drive", SongTwoName: "I Got U", SongThreeName: "Need U", SongFourName: "The Giver", SongFiveName: "Won’t Look Back", Day: "Day 2"))
            arrayOfAllBands.append(DetailBandClass(Name: "Foals", Genre: "Rock", SongOneURL: "https://www.youtube.com/watch?v=l_EIE5f2t6M", SongTwoURL: "https://www.youtube.com/watch?v=eYoINidnLRQ", SongThreeURL: "https://www.youtube.com/watch?v=bAsGFnLl2u0", SongFourURL: "https://www.youtube.com/watch?v=iuQQIawCqBA", SongFiveURL: "https://www.youtube.com/watch?v=m5KQOGHXkgw", SongOneName: "Mountain At My Gates", SongTwoName: "Spanish Sahara", SongThreeName: "My Number", SongFourName: "What Went Down", SongFiveName: "Prelude", Day: "Day 2"))
            arrayOfAllBands.append(DetailBandClass(Name: "Frank Turner", Genre: "Alternative", SongOneURL: "https://www.youtube.com/watch?v=tB4Avdlz3lk", SongTwoURL: "https://www.youtube.com/watch?v=P4IZbCl6iR4", SongThreeURL: "https://www.youtube.com/watch?v=Cf5O2M5GaEA", SongFourURL: "https://www.youtube.com/watch?v=0LQVMRoglIo", SongFiveURL: "https://www.youtube.com/watch?v=F1L5zJ2afLs", SongOneName: "Get Better", SongTwoName: "The Next Storm", SongThreeName: "The Way I tend To Be", SongFourName: "Song For Josh", SongFiveName: "Recovery", Day: "Day 2"))
            arrayOfAllBands.append(DetailBandClass(Name: "Frightened Rabbit", Genre: "Rock", SongOneURL: "https://www.youtube.com/watch?v=J8fVX41-Njg", SongTwoURL: "https://www.youtube.com/watch?v=SzjERZU3wbY", SongThreeURL: "https://www.youtube.com/watch?v=KY4j8Ow-CTs", SongFourURL: "https://www.youtube.com/watch?v=y3xadvsaS_Q", SongFiveURL: "https://www.youtube.com/watch?v=aTXA_q12hKg", SongOneName: "Keep YourSelf Warm", SongTwoName: "Swim Until You Can’t See land", SongThreeName: "The WoodPile", SongFourName: "Fuck This Place", SongFiveName: "Backwards Walk", Day: "Day 2"))
            arrayOfAllBands.append(DetailBandClass(Name: "Future", Genre: "Hip Hop", SongOneURL: "https://www.youtube.com/watch?v=I8IhkhLvvho", SongTwoURL: "https://www.youtube.com/watch?v=NkfHxKw6dYg", SongThreeURL: "https://www.youtube.com/watch?v=S-T2f-136mA", SongFourURL: "https://www.youtube.com/watch?v=iJK0OGlhKF4", SongFiveURL: "https://www.youtube.com/watch?v=DXXZ3J_QIGw", SongOneName: "March Madness", SongTwoName: "Just Like Bruddas", SongThreeName: "News Or Somthn", SongFourName: "Trap Niggas", SongFiveName: "56 Nights", Day: "Day 2"))
            arrayOfAllBands.append(DetailBandClass(Name: "Ghost", Genre: "Rock", SongOneURL: "https://www.youtube.com/watch?v=-0Ao4t_fe0I", SongTwoURL: "http://www.vevo.com/watch/ghost-bc/year-zero/USUV71300503", SongThreeURL: "https://www.youtube.com/watch?v=6A-IoOEPbUs", SongFourURL: "https://www.youtube.com/watch?v=Dxr5sKyK8ys", SongFiveURL: "https://www.youtube.com/watch?v=vyQZ13jobIY", SongOneName: "Cirice", SongTwoName: "Year Zero", SongThreeName: "From The Pinnacle To The Pit", SongFourName: "Monstrance Clock", SongFiveName: "Secular Haze", Day: "Day 2"))
            arrayOfAllBands.append(DetailBandClass(Name: "Griz", Genre: "Electronic", SongOneURL: "https://www.youtube.com/watch?v=p8P28RXa3zY", SongTwoURL: "https://www.youtube.com/watch?v=y6n0XsiX_QQ", SongThreeURL: "https://www.youtube.com/watch?v=77fOPps7yus", SongFourURL: "https://www.youtube.com/watch?v=NeG89FKJEq4", SongFiveURL: "https://www.youtube.com/watch?v=UsSzq5h2-tc", SongOneName: "Stop Trippin ", SongTwoName: "Gettin’ Live", SongThreeName: "Good Times Roll", SongFourName: "A Fine Way To Die", SongFiveName: "Smash The Funk", Day: "Day 2"))
            arrayOfAllBands.append(DetailBandClass(Name: "Haelos", Genre: "Electronic", SongOneURL: "https://www.youtube.com/watch?v=uXTFP4wcjdA", SongTwoURL: "https://www.youtube.com/watch?v=KPOHKkxgPsQ", SongThreeURL: "https://www.youtube.com/watch?v=vKakNhz2ToA", SongFourURL: "https://www.youtube.com/watch?v=IY0JVKORfR4", SongFiveURL: "https://www.youtube.com/watch?v=HmzveKLF9Fk", SongOneName: "Dust", SongTwoName: "Earth Not Above", SongThreeName: "Pray", SongFourName: "SEPARATE LIVES", SongFiveName: "Ethyr", Day: "Day 2"))
            arrayOfAllBands.append(DetailBandClass(Name: "Hayden James", Genre: "House", SongOneURL: "https://www.youtube.com/watch?v=Hyi8Z4s2miw", SongTwoURL: "https://www.youtube.com/watch?v=MfttyNSCI-g", SongThreeURL: "https://www.youtube.com/watch?v=stNRPseb_Mg", SongFourURL: "https://www.youtube.com/watch?v=idKjrBwuWFM", SongFiveURL: "https://www.youtube.com/watch?v=C_GUj12tdtA", SongOneName: "Something About You", SongTwoName: "Permission to Love", SongThreeName: "Embrace", SongFourName: "Beginnings", SongFiveName: "No Time", Day: "Day 2"))
            arrayOfAllBands.append(DetailBandClass(Name: "Illenium", Genre: "Electronic", SongOneURL: "https://www.youtube.com/watch?v=hgozboU7ne0", SongTwoURL: "https://www.youtube.com/watch?v=81uHlxzM6KE", SongThreeURL: "https://www.youtube.com/watch?v=Xe-KCnjp2AA", SongFourURL: "https://www.youtube.com/watch?v=m5UDehvPzLE", SongFiveURL: "https://www.youtube.com/watch?v=BfY7TfeGqV0", SongOneName: "Ill Be Your Reason", SongTwoName: "All On U", SongThreeName: "In Your Wake", SongFourName: "Drop Our Hearts", SongFiveName: "SleepWalker", Day: "Day 2"))
            arrayOfAllBands.append(DetailBandClass(Name: "Lettuce", Genre: "Pop", SongOneURL: "https://www.youtube.com/watch?v=Xy_eAqPgC3o", SongTwoURL: "https://www.youtube.com/watch?v=Tyt_4N4LNz4", SongThreeURL: "https://www.youtube.com/watch?v=Y3ohZjCKzjg", SongFourURL: "https://www.youtube.com/watch?v=FPG9ax85sIo", SongFiveURL: "https://www.youtube.com/watch?v=95XAyPL_bt4", SongOneName: "Brain Reaction", SongTwoName: "Do it Like You Do", SongThreeName: "Lettsanity", SongFourName: "Fly", SongFiveName: "Ziggowatt", Day: "Day 2"))
            arrayOfAllBands.append(DetailBandClass(Name: "Lewis Del Mar", Genre: "Rock", SongOneURL: "https://www.youtube.com/watch?v=vVFwuq44UTQ", SongTwoURL: "https://www.youtube.com/watch?v=XGrpK-sQD3E", SongThreeURL: "https://www.youtube.com/watch?v=_63uM8Vl4sg", SongFourURL: "https://www.youtube.com/watch?v=q0hx0VdU60U", SongFiveURL: "", SongOneName: "Loud", SongTwoName: "Wave", SongThreeName: "Malt Liquor ", SongFourName: "Memories", SongFiveName: "", Day: "Day 2"))
            arrayOfAllBands.append(DetailBandClass(Name: "M83", Genre: "Rock", SongOneURL: "https://www.youtube.com/watch?v=dX3k_QDnzHE", SongTwoURL: "https://www.youtube.com/watch?v=lAwYodrBr2Q", SongThreeURL: "https://www.youtube.com/watch?v=ryh9rkIRGUs", SongFourURL: "https://www.youtube.com/watch?v=DJQQrjVmQG0", SongFiveURL: "https://www.youtube.com/watch?v=1DJ3-BVMjOs", SongOneName: "Midnight City", SongTwoName: "Wait", SongThreeName: "Do It, Try It", SongFourName: "Reunion", SongFiveName: "Outro", Day: "Day 2"))
            arrayOfAllBands.append(DetailBandClass(Name: "Mac Miller", Genre: "Rap", SongOneURL: "https://www.youtube.com/watch?v=74TFS8r_SMI", SongTwoURL: "https://www.youtube.com/watch?v=N29-54dhVHg", SongThreeURL: "https://www.youtube.com/watch?v=a-rqu-hjobc", SongFourURL: "https://www.youtube.com/watch?v=lp72KlZ6-Io", SongFiveURL: "https://www.youtube.com/watch?v=_BYIEXzdnlY", SongOneName: "Donald Trump", SongTwoName: "Weekend", SongThreeName: "Nikes On My Feet", SongFourName: "100 Grand Kids", SongFiveName: "Loud", Day: "Day 2"))
            arrayOfAllBands.append(DetailBandClass(Name: "Major Lazer", Genre: "Electronic", SongOneURL: "https://www.youtube.com/watch?v=YqeW9_5kURI", SongTwoURL: "https://www.youtube.com/watch?v=qDcFryDXQ7U", SongThreeURL: "https://www.youtube.com/watch?v=Y7OCgi7rANc", SongFourURL: "https://www.youtube.com/watch?v=wO89_H7GqaQ", SongFiveURL: "https://www.youtube.com/watch?v=_zCoCa6b6cU", SongOneName: "Lean On", SongTwoName: "Light It Upl", SongThreeName: "Powerful", SongFourName: "Bubble Butt", SongFiveName: "Watch For This", Day: "Day 2"))
            arrayOfAllBands.append(DetailBandClass(Name: "Martin Garrix", Genre: "House", SongOneURL: "https://www.youtube.com/watch?v=gCYcHz2k5x0", SongTwoURL: "https://www.youtube.com/watch?v=dzHdo4yxidc", SongThreeURL: "https://www.youtube.com/watch?v=nJSdYlAFKqA", SongFourURL: "https://www.youtube.com/watch?v=Zv1QV6lrc_Y", SongFiveURL: "https://www.youtube.com/watch?v=9vMh9f41pqE", SongOneName: "Animals", SongTwoName: "Turn Up The Speakers", SongThreeName: "Dont Look Down", SongFourName: "Forbidden Voices", SongFiveName: "Tremor", Day: "Day 2"))
            arrayOfAllBands.append(DetailBandClass(Name: "Miike Snow", Genre: "Pop", SongOneURL: "https://www.youtube.com/watch?v=P_SlAzsXa7E", SongTwoURL: "https://www.youtube.com/watch?v=mVWeqAPQUXc", SongThreeURL: "https://www.youtube.com/watch?v=EWJHK0JT_Xc", SongFourURL: "https://www.youtube.com/watch?v=i6KEahxi1fE", SongFiveURL: "https://www.youtube.com/watch?v=8oKQSAt4c4c", SongOneName: "Genghis Khan", SongTwoName: "Animal", SongThreeName: "Heart Is Full", SongFourName: "Song For No One", SongFiveName: "Black & Blue", Day: "Day 2"))
            arrayOfAllBands.append(DetailBandClass(Name: "Modern Baseball", Genre: "Rock", SongOneURL: "https://www.youtube.com/watch?v=MbrUzJlTffs", SongTwoURL: "https://www.youtube.com/watch?v=kU3UFfTDVY8", SongThreeURL: "https://www.youtube.com/watch?v=munEaFvfbnE", SongFourURL: "https://www.youtube.com/watch?v=cIy2wyEV0qc", SongFiveURL: "https://www.youtube.com/watch?v=EQ7NOmRKuAE", SongOneName: "Your Graduation", SongTwoName: "Teers Over Beers", SongThreeName: "Fine, Great", SongFourName: "The Weekend", SongFiveName: "The Trash Particale", Day: "Day 2"))
            arrayOfAllBands.append(DetailBandClass(Name: "Mute Math", Genre: "Rock", SongOneURL: "https://www.youtube.com/watch?v=ADrBzG69wEg", SongTwoURL: "https://www.youtube.com/watch?v=Ry6GAwDCI2I", SongThreeURL: "https://www.youtube.com/watch?v=fMiOi8KKkKw", SongFourURL: "https://www.youtube.com/watch?v=biIKL3qh0L4", SongFiveURL: "https://www.youtube.com/watch?v=t6i6TBT4kfg", SongOneName: "Prytania", SongTwoName: "Spotlight", SongThreeName: "You Are Mine", SongFourName: "Typical", SongFiveName: "Monument", Day: "Day 3"))
            arrayOfAllBands.append(DetailBandClass(Name: "MØ", Genre: "Pop", SongOneURL: "https://www.youtube.com/watch?v=EZI8D_pBMRc", SongTwoURL: "https://www.youtube.com/watch?v=wFrth4NFogc", SongThreeURL: "https://www.youtube.com/watch?v=gc7SfWGT-ak", SongFourURL: "https://www.youtube.com/watch?v=mHWr4WY9o24", SongFiveURL: "https://www.youtube.com/watch?v=M5uIVBxWZVU", SongOneName: "XXX 88", SongTwoName: "Waste Of Time", SongThreeName: "Don’t Want To Dance", SongFourName: "Walk This Way", SongFiveName: "Pilgrim", Day: "Day 2 "))
            arrayOfAllBands.append(DetailBandClass(Name: "Party Favor", Genre: "Electronic", SongOneURL: "https://www.youtube.com/watch?v=fz7dttXLaOE", SongTwoURL: "https://www.youtube.com/watch?v=uZIPW2t1W5o", SongThreeURL: "https://www.youtube.com/watch?v=b61XdGPZV18", SongFourURL: "https://www.youtube.com/watch?v=dZC9tdmFYtE", SongFiveURL: "https://www.youtube.com/watch?v=tnUA2VWWgMY", SongOneName: "Bap U", SongTwoName: "Booty Loose", SongThreeName: "Baddest Things", SongFourName: "Sweat", SongFiveName: "Bust ‘Em", Day: "Day 2"))
            arrayOfAllBands.append(DetailBandClass(Name: "Pvris", Genre: "Rock", SongOneURL: "https://www.youtube.com/watch?v=8aQz-aKvyQU", SongTwoURL: "https://www.youtube.com/watch?v=nJ3jl794mGs", SongThreeURL: "https://www.youtube.com/watch?v=j2SWk859CEU", SongFourURL: "https://www.youtube.com/watch?v=D0NqJgcbHe8", SongFiveURL: "https://www.youtube.com/watch?v=9ibcG-YAUfI", SongOneName: "My House", SongTwoName: "White Noise", SongThreeName: "St. Patrick", SongFourName: "You and I", SongFiveName: "Eyelids", Day: "Day 2"))
            arrayOfAllBands.append(DetailBandClass(Name: "RadioHead", Genre: "Rock", SongOneURL: "https://www.youtube.com/watch?v=XFkzRNyygfk", SongTwoURL: "https://www.youtube.com/watch?v=IBH97ma9YiI", SongThreeURL: "https://www.youtube.com/watch?v=u5CVsCnxyXg", SongFourURL: "https://www.youtube.com/watch?v=sPLEbAVjiLA", SongFiveURL: "https://www.youtube.com/watch?v=n5h0qHwNrHk", SongOneName: "Creep", SongTwoName: "Karma Police", SongThreeName: "No Surprises", SongFourName: "Paranoid Android", SongFiveName: "Fake Plastic Trees", Day: "Day 2"))
            arrayOfAllBands.append(DetailBandClass(Name: "Rufus Du Sol", Genre: "Alternative", SongOneURL: "https://www.youtube.com/watch?v=5XS5dzDa56E", SongTwoURL: "https://www.youtube.com/watch?v=-iveEQB8PQc", SongThreeURL: "https://www.youtube.com/watch?v=EezbXuGwD3I", SongFourURL: "https://www.youtube.com/watch?v=LVXKO8DGOKk", SongFiveURL: "https://www.youtube.com/watch?v=iUkXe0bRjsg", SongOneName: "Like An Animal", SongTwoName: "You Were Right", SongThreeName: "Inner Bloom", SongFourName: "Modest Life", SongFiveName: "Say a Prayer For Me", Day: "Day 2"))
            arrayOfAllBands.append(DetailBandClass(Name: "Saba", Genre: "Rap", SongOneURL: "https://www.youtube.com/watch?v=eedeXTWZUn8", SongTwoURL: "https://www.youtube.com/watch?v=QjV0BQ53A1g", SongThreeURL: "https://www.youtube.com/watch?v=zUorKpOuoro", SongFourURL: "https://www.youtube.com/watch?v=-FQfvhgoPek", SongFiveURL: "https://www.youtube.com/watch?v=EvH5fvkgNbE", SongOneName: "Chance The Rapper", SongTwoName: "Butter", SongThreeName: "Angles", SongFourName: "Comfort Zone", SongFiveName: "Cursive", Day: "Day 2"))
            arrayOfAllBands.append(DetailBandClass(Name: "Saint Motel", Genre: "Rock", SongOneURL: "https://www.youtube.com/watch?v=IyVPyKrx0Xo", SongTwoURL: "https://www.youtube.com/watch?v=Of3jUuQzH2o", SongThreeURL: "https://www.youtube.com/watch?v=n7bQGM14mJI", SongFourURL: "https://www.youtube.com/watch?v=6-8UgDUKcOs", SongFiveURL: "https://www.youtube.com/watch?v=aKTBMY52DYA", SongOneName: "My Type", SongTwoName: "Cold Cold Man", SongThreeName: "Puzzle Pieces", SongFourName: "Benny Goodman", SongFiveName: "Ace In the Hole", Day: "Day 2"))
            arrayOfAllBands.append(DetailBandClass(Name: "Skepta", Genre: "Rap", SongOneURL: "https://www.youtube.com/watch?v=_xQKWnvtg6c", SongTwoURL: "https://www.youtube.com/watch?v=4eMeVQjTlgQ", SongThreeURL: "https://www.youtube.com/watch?v=sOhxPhqzMwg", SongFourURL: "https://www.youtube.com/watch?v=RYfXt3Z-uew", SongFiveURL: "https://www.youtube.com/watch?v=czLQoG01PFs", SongOneName: "Thats Not Me", SongTwoName: "Ladies Hit Squad", SongThreeName: "Man", SongFourName: "All Over The House", SongFiveName: "It Aint Safe", Day: "Day 2"))
            arrayOfAllBands.append(DetailBandClass(Name: "Sunflower Bean", Genre: "Rock", SongOneURL: "https://www.youtube.com/watch?v=xykuu_pVZak", SongTwoURL: "https://www.youtube.com/watch?v=8RplDJ08s8Y", SongThreeURL: "https://www.youtube.com/watch?v=qOIZEHfM_fw", SongFourURL: "https://www.youtube.com/watch?v=3cLUGjtqAmE", SongFiveURL: "https://www.youtube.com/watch?v=P2tmNib3bZY", SongOneName: "Easier Said", SongTwoName: "Wall Watcher", SongThreeName: "Human Ceremony", SongFourName: "This Kind Of Feeling", SongFiveName: "Space Exploration Disaster", Day: "Day 2"))
            arrayOfAllBands.append(DetailBandClass(Name: "The Struts", Genre: "Rock", SongOneURL: "https://www.youtube.com/watch?v=ARhk9K_mviE", SongTwoURL: "https://www.youtube.com/watch?v=r61Xj0pHawE", SongThreeURL: "https://www.youtube.com/watch?v=9GuUbziASwE", SongFourURL: "https://www.youtube.com/watch?v=h6xPr2FpCrY", SongFiveURL: "https://www.youtube.com/watch?v=jOPPq90khJA", SongOneName: "Could Have Been Me", SongTwoName: "Kiss This", SongThreeName: "Put Your Money On Me", SongFourName: "Where Did She Go", SongFiveName: "Only Just A Call Away", Day: "Day 2"))
        }
        if title1 == "Day 3"
        {
            arrayOfAllBands.append(DetailBandClass(Name: "AC Slater", Genre: "House", SongOneURL: "https://www.youtube.com/watch?v=Z-O0Z2icWM0", SongTwoURL: "https://www.youtube.com/watch?v=KtsJdisuFgw", SongThreeURL: "https://www.youtube.com/watch?v=Xhb0wepHdzs", SongFourURL: "https://www.youtube.com/watch?v=xHTbqAfFbVo", SongFiveURL: "https://www.youtube.com/watch?v=PRqRTtyKPMg", SongOneName: "Calm Down", SongTwoName: "Jack Got Jacked (Jack Beats Remix)", SongThreeName: "Up Against The Wall feat. Lismore (Wonk Remix)", SongFourName: "Bass Inside", SongFiveName: "U Got 2", Day: "Day 3"))
            arrayOfAllBands.append(DetailBandClass(Name: "Alina Baraz", Genre: "Alternative", SongOneURL: "https://www.youtube.com/watch?v=NiqtgWWL6u8", SongTwoURL: "https://www.youtube.com/watch?v=D5q2eRU5Y5c", SongThreeURL: "https://www.youtube.com/watch?v=MUmjKCjeu1A", SongFourURL: "https://www.youtube.com/watch?v=p6_vULXtMig", SongFiveURL: "https://www.youtube.com/watch?v=JrHw9BDa3OE", SongOneName: "Fantasy", SongTwoName: "Fantasy - Felix Jaehn Remix ", SongThreeName: "Make You Feel", SongFourName: "Fantasy - Vices Remix", SongFiveName: " Pretty Thoughts", Day: "Day 3"))
            arrayOfAllBands.append(DetailBandClass(Name: "Baid", Genre: "Rock", SongOneURL: "https://www.youtube.com/watch?v=xzMmep2KFYE", SongTwoURL: "https://www.youtube.com/watch?v=wd_G4krhb_A", SongThreeURL: "https://www.youtube.com/watch?v=cnjlofyAfUo", SongFourURL: "https://www.youtube.com/watch?v=Bs9neeZV9fU", SongFiveURL: "https://www.youtube.com/watch?v=wL27Gis-Cyw", SongOneName: "Sister of Pearl", SongTwoName: "Sunburn Modern", SongThreeName: "Brainwash yyrr Face", SongFourName: "The Names", SongFiveName: "Endless Rythm", Day: "Day 3"))
            arrayOfAllBands.append(DetailBandClass(Name: "Big Gigantic", Genre: "Hip Hop", SongOneURL: "https://www.youtube.com/watch?v=xPrgVald-fc", SongTwoURL: "https://www.youtube.com/watch?v=y3Ut46W52h8", SongThreeURL: "https://www.youtube.com/watch?v=qlBUMXVZhMA", SongFourURL: "https://www.youtube.com/watch?v=nO0ZuNSFduc", SongFiveURL: "https://www.youtube.com/watch?v=RNp0KlJX6JE", SongOneName: "Sky High", SongTwoName: "Its Goin Down", SongThreeName: "Thinking Out Loud", SongFourName: "Lucid Dreams", SongFiveName: "Fire It Up", Day: "Day 3"))
            arrayOfAllBands.append(DetailBandClass(Name: "Big Grams", Genre: "Hip Hop", SongOneURL: "https://www.youtube.com/watch?v=xpmE0Qiup3U", SongTwoURL: "https://www.youtube.com/watch?v=djbFQKzkiRg", SongThreeURL: "https://www.youtube.com/watch?v=pIG2_N1drc4", SongFourURL: "https://www.youtube.com/watch?v=hruW7-mYWhY", SongFiveURL: "https://www.youtube.com/watch?v=ajJDcded23g", SongOneName: "Lights On", SongTwoName: "Fell In the Sun", SongThreeName: "Goldmine Junkie", SongFourName: "Born to Shine", SongFiveName: "Run For Your Life", Day: "Day 3"))
            arrayOfAllBands.append(DetailBandClass(Name: "Chair Lift", Genre: "Pop", SongOneURL: "https://www.youtube.com/watch?v=w8HRCacAQ-4", SongTwoURL: "https://www.youtube.com/watch?v=j_aTOyFRwJ0", SongThreeURL: "https://www.youtube.com/watch?v=98XRKr19jIE", SongFourURL: "https://www.youtube.com/watch?v=mvqakws0CeU", SongFiveURL: "https://www.youtube.com/watch?v=GrM5SOGw9T8", SongOneName: "Bruises", SongTwoName: "I Belong In Your Arms", SongThreeName: "Amanaemonesia", SongFourName: "Evident Utensil", SongFiveName: "Sidewalk Safari", Day: "Day 3"))
            arrayOfAllBands.append(DetailBandClass(Name: "Chris Stapleton", Genre: "Rock", SongOneURL: "https://www.youtube.com/watch?v=4zAThXFOy2c", SongTwoURL: "https://www.youtube.com/watch?v=_kBnFgLP8po", SongThreeURL: "https://www.youtube.com/watch?v=etD0Y_8vyxg", SongFourURL: "https://www.youtube.com/watch?v=ymqPEoFwhpU", SongFiveURL: "https://www.youtube.com/watch?v=6pNSOyrkX5w", SongOneName: "Tennessee Whiskey", SongTwoName: "Traveller", SongThreeName: "Nobody to Blame", SongFourName: "Whiskey and You", SongFiveName: "More Of You", Day: "Day 3"))
            arrayOfAllBands.append(DetailBandClass(Name: "Disclosure", Genre: "House", SongOneURL: "https://www.youtube.com/watch?v=fB63ztKnGvo", SongTwoURL: "https://www.youtube.com/watch?v=93ASUImTedo", SongThreeURL: "https://www.youtube.com/watch?v=_zPlr-o-YEQ", SongFourURL: "https://www.youtube.com/watch?v=b_KfnGBtVeA", SongFiveURL: "https://www.youtube.com/watch?v=4nsKDJlpUbA", SongOneName: "Omen", SongTwoName: "Latch", SongThreeName: "You & Me", SongFourName: "Magnets", SongFiveName: "When A Fire Starts To Burn", Day: "Day 3"))
            arrayOfAllBands.append(DetailBandClass(Name: "Drowners", Genre: "Rock", SongOneURL: "https://www.youtube.com/watch?v=VuFYXj5k8ug", SongTwoURL: "https://www.youtube.com/watch?v=b-AgW4E7cNY", SongThreeURL: "https://www.youtube.com/watch?v=SMquKngK_Fk", SongFourURL: "https://www.youtube.com/watch?v=mVj_MRGNa4c", SongFiveURL: "https://www.youtube.com/watch?v=NkP7kwMKRWo", SongOneName: "Luv, Hold Me Down", SongTwoName: "A Button On Your Blouse", SongThreeName: "Cruel Ways", SongFourName: "Unzip Your Harrington", SongFiveName: "Long Hair", Day: "Day 3"))
            arrayOfAllBands.append(DetailBandClass(Name: "Dua Lipa", Genre: "Pop", SongOneURL: "https://www.youtube.com/watch?v=-rey3m8SWQI", SongTwoURL: "https://www.youtube.com/watch?v=lwZqbQL4H4Q", SongThreeURL: "https://www.youtube.com/watch?v=Nz-dPOjK1gQ", SongFourURL: "", SongFiveURL: "", SongOneName: "Be The One", SongTwoName: "Last Dance", SongThreeName: "New Love", SongFourName: "", SongFiveName: "", Day: "Day 3"))
            arrayOfAllBands.append(DetailBandClass(Name: "Generik", Genre: "Electronic", SongOneURL: "https://www.youtube.com/watch?v=_m1HqYHh5Dc", SongTwoURL: "https://soundcloud.com/generik_dj/generik-late-at-night-1", SongThreeURL: "https://soundcloud.com/generik_dj/hayden-james-something-about-you-generik-remix", SongFourURL: "https://soundcloud.com/generik_dj/yolanda-be-cool-sugar-man-generik-remix", SongFiveURL: "https://soundcloud.com/generik_dj/drop-the-lime-set-me-free-generik-homo-house-remix", SongOneName: "The Weekend", SongTwoName: "Late At Night", SongThreeName: "Something About You (Generik Remix)", SongFourName: "Sugar Man (Generik Remix)", SongFiveName: "Set Me Free (Generik Remix)", Day: "Day 3"))
            arrayOfAllBands.append(DetailBandClass(Name: "Grimes", Genre: "Electronic", SongOneURL: "https://www.youtube.com/watch?v=c2EJMd7ZN7w", SongTwoURL: "https://www.youtube.com/watch?v=Tv9YoYCKNoE", SongThreeURL: "https://www.youtube.com/watch?v=N9XKLqGqwLA", SongFourURL: "https://www.youtube.com/watch?v=JtH68PJIQLE", SongFiveURL: "https://www.youtube.com/watch?v=1FH-q0I1fJY", SongOneName: "Kill V Maim", SongTwoName: "Flesh Without Blood", SongThreeName: "Realiti", SongFourName: "Oblivion", SongFiveName: "Genesis", Day: "Day 3"))
            arrayOfAllBands.append(DetailBandClass(Name: "Hardwell", Genre: "House", SongOneURL: "https://www.youtube.com/watch?v=ppy-fgbPn2s", SongTwoURL: "https://www.youtube.com/watch?v=AQ0resnXCcE", SongThreeURL: "https://www.youtube.com/watch?v=lETmskoqh30", SongFourURL: "https://www.youtube.com/watch?v=ULwcsIPdc8w", SongFiveURL: "https://www.youtube.com/watch?v=Ox_rgDuyws8", SongOneName: "Call Me a Spaceman", SongTwoName: "Young Again", SongThreeName: "Spaceman", SongFourName: "Run Wild", SongFiveName: "Sally", Day: "Day 3"))
            arrayOfAllBands.append(DetailBandClass(Name: "Hound Mouth", Genre: "Rock", SongOneURL: "https://www.youtube.com/watch?v=Y8wifV5RYr8", SongTwoURL: "https://www.youtube.com/watch?v=hws_N4St0BU", SongThreeURL: "https://www.youtube.com/watch?v=lSccfq31t7w", SongFourURL: "https://www.youtube.com/watch?v=a6D_-1wk-MY", SongFiveURL: "https://www.youtube.com/watch?v=8cqVU7Bevic", SongOneName: "Sedona", SongTwoName: "Penitentiary", SongThreeName: "Casino", SongFourName: "Say It", SongFiveName: "My Cousin Greg", Day: "Day 3"))
            arrayOfAllBands.append(DetailBandClass(Name: "Jack Garratt", Genre: "Pop", SongOneURL: "https://www.youtube.com/watch?v=hFP3qh1x1Zo", SongTwoURL: "https://www.youtube.com/watch?v=H6bjwDFk8mo", SongThreeURL: "https://www.youtube.com/watch?v=ZqtvrsNLFMs", SongFourURL: "https://www.youtube.com/watch?v=bOWWLytfmnU", SongFiveURL: "https://www.youtube.com/watch?v=hL8B98PuszY", SongOneName: "Worry", SongTwoName: "Wheatherd", SongThreeName: "Breathe Life", SongFourName: "The Love You're Given", SongFiveName: "Remnants", Day: "Day 3"))
            arrayOfAllBands.append(DetailBandClass(Name: "Janes Addiction", Genre: "Rock", SongOneURL: "https://www.youtube.com/watch?v=anWmfN-dODs", SongTwoURL: "https://www.youtube.com/watch?v=jrwjiO1MCVs", SongThreeURL: "https://www.youtube.com/watch?v=1kAIMlISHhU", SongFourURL: "https://www.youtube.com/watch?v=sb3FJdRk-tI", SongFiveURL: "https://www.youtube.com/watch?v=V9ROmxvSYr4", SongOneName: "Jane Says ", SongTwoName: "Been Caught Stealing", SongThreeName: "Mountain Song ", SongFourName: "Just Because", SongFiveName: "Sympathy", Day: "Day 3"))
            arrayOfAllBands.append(DetailBandClass(Name: "Jarryd James", Genre: "Alternative", SongOneURL: "https://www.youtube.com/watch?v=QQ7XJG0Z2ho", SongTwoURL: "https://www.youtube.com/watch?v=f43T6OuM3hI", SongThreeURL: "https://www.youtube.com/watch?v=U5mHGbjsqUc", SongFourURL: "https://www.youtube.com/watch?v=EVgyiuFYKXc", SongFiveURL: "https://www.youtube.com/watch?v=U0l_GIvv_oY", SongOneName: "Do You Remeber", SongTwoName: "Give Me Something", SongThreeName: "Regardless", SongFourName: "This Time", SongFiveName: "Sure Love", Day: "Day 3"))
            arrayOfAllBands.append(DetailBandClass(Name: "Jauz", Genre: "House", SongOneURL: "https://www.youtube.com/watch?v=jHyvlBDv3CI", SongTwoURL: "https://www.youtube.com/watch?v=jHyvlBDv3CI", SongThreeURL: "https://www.youtube.com/watch?v=p2cDjhA8sP4", SongFourURL: "https://www.youtube.com/watch?v=hkYq02183fc", SongFiveURL: "https://www.youtube.com/watch?v=HkYjFCZrM68", SongOneName: "Sqaud Out", SongTwoName: "Get On Up", SongThreeName: "Deeper Love", SongFourName: "Feel The Volume", SongFiveName: "Rock The Party (Radio Edit)", Day: "Day 3"))
            arrayOfAllBands.append(DetailBandClass(Name: "Leon Bridges", Genre: "Alternative", SongOneURL: "https://www.youtube.com/watch?v=MTrKkqE9p1o", SongTwoURL: "https://www.youtube.com/watch?v=HYplnRjMVhM", SongThreeURL: "https://www.youtube.com/watch?v=jPdzSFEVQss", SongFourURL: "https://www.youtube.com/watch?v=0Hegd4xNfRo", SongFiveURL: "https://www.youtube.com/watch?v=pgS_xob1x4A", SongOneName: "Coming Home", SongTwoName: "Smooth Sailin” ", SongThreeName: "Lisa Sawyer", SongFourName: "River", SongFiveName: "Better Men", Day: "Day 3"))
            arrayOfAllBands.append(DetailBandClass(Name: "LOLAWOLF", Genre: "Electronic", SongOneURL: "https://www.youtube.com/watch?v=eg_-IVEZwcU", SongTwoURL: "", SongThreeURL: "https://www.youtube.com/watch?v=OQmYSMfrgw4", SongFourURL: "https://www.youtube.com/watch?v=PeELcIi_LIg", SongFiveURL: "https://www.youtube.com/watch?v=FYekhopaJCU", SongOneName: "Jimmy Franco", SongTwoName: "Every Fucking Day", SongThreeName: "Dirty Feeling", SongFourName: "Bitch", SongFiveName: "AYO", Day: "Day 3"))
            arrayOfAllBands.append(DetailBandClass(Name: "Marshmello", Genre: "House", SongOneURL: "https://www.youtube.com/watch?v=x4J14C1Cmek", SongTwoURL: "https://www.youtube.com/watch?v=hLasSZjcvzY", SongThreeURL: "https://www.youtube.com/watch?v=C2cv-8vqv7k", SongFourURL: "https://www.youtube.com/watch?v=V4QKO5KlBJc", SongFiveURL: "https://www.youtube.com/watch?v=B1eAqV8w1KU", SongOneName: "Keep It Mello", SongTwoName: "Want U 2", SongThreeName: "Summer", SongFourName: "Kknow Me", SongFiveName: "Find Me", Day: "Day 3"))
            arrayOfAllBands.append(DetailBandClass(Name: "Nathaniel Rateliff", Genre: "Alternative", SongOneURL: "https://www.youtube.com/watch?v=8LNe5HQTQX0", SongTwoURL: "https://www.youtube.com/watch?v=vjM0xggoY9E", SongThreeURL: "https://www.youtube.com/watch?v=nFhC3Xuq_6Y", SongFourURL: "https://www.youtube.com/watch?v=UBdswnPRf78", SongFiveURL: "https://www.youtube.com/watch?v=b5Q_Zg_QArM", SongOneName: "Look It Here", SongTwoName: "Still Trying", SongThreeName: "Trying So Hard Not To Know ", SongFourName: "Mellow Out", SongFiveName: "Falling Faster Than You Can Run", Day: "Day 3"))
            arrayOfAllBands.append(DetailBandClass(Name: "Nothing", Genre: "Rock", SongOneURL: "https://www.youtube.com/watch?v=QOexw4cXfoY", SongTwoURL: "https://www.youtube.com/watch?v=WjM0SRPXSUo", SongThreeURL: "https://www.youtube.com/watch?v=AsajdazBhKo", SongFourURL: "https://www.youtube.com/watch?v=tHE4T0zOWgo", SongFiveURL: "https://www.youtube.com/watch?v=PjNyY9G3BBA", SongOneName: "Bent Nail", SongTwoName: "Vertigue Flowers", SongThreeName: "Get Well", SongFourName: "Downward Years To Come", SongFiveName: "Hymn To The Pillory", Day: "Day 3 "))
            arrayOfAllBands.append(DetailBandClass(Name: "Nothing But Thieves", Genre: "Rock", SongOneURL: "https://www.youtube.com/watch?v=w1Qxxx2SQoo", SongTwoURL: "https://www.youtube.com/watch?v=DCCAEcuOk_g", SongThreeURL: "https://www.youtube.com/watch?v=xNjFXqiQ0-U", SongFourURL: "https://www.youtube.com/watch?v=dRdCdCtdMiU", SongFiveURL: "https://www.youtube.com/watch?v=i1A0G1d8Kzw", SongOneName: "Trip Switch", SongTwoName: "Graveyard Whistleing", SongThreeName: "If  I Get High", SongFourName: "Ban All The Music", SongFiveName: "Lover, Please Stay", Day: "Day 3"))
            arrayOfAllBands.append(DetailBandClass(Name: "Oliver Heldens", Genre: "House", SongOneURL: "https://www.youtube.com/watch?v=JxEiIeoet6Q", SongTwoURL: "https://www.youtube.com/watch?v=oCwjnyrfudY", SongThreeURL: "https://www.youtube.com/watch?v=jjx2oc2NRzA", SongFourURL: "https://www.youtube.com/watch?v=NoDc0RC02CQ", SongFiveURL: "https://www.youtube.com/watch?v=wQyWgeFtWls", SongOneName: "The Right Song", SongTwoName: "Wombass", SongThreeName: "Gecko", SongFourName: "Shades Of Grey", SongFiveName: "Koala", Day: "Day 3"))
            arrayOfAllBands.append(DetailBandClass(Name: "Red Hot Chilli Peppers", Genre: "Rock", SongOneURL: "https://www.youtube.com/watch?v=lwlogyj7nFE", SongTwoURL: "https://www.youtube.com/watch?v=YlUKcNNmywk", SongThreeURL: "https://www.youtube.com/watch?v=o7MhpFF1vv0", SongFourURL: "https://www.youtube.com/watch?v=rn_YodiJO6k", SongFiveURL: "https://www.youtube.com/watch?v=BfOdWSiyWoc", SongOneName: "Under the Bridge", SongTwoName: "Californication", SongThreeName: "Snow (Hey Oh)", SongFourName: "Otherside", SongFiveName: "Can’t Stop", Day: "Day 3"))
            arrayOfAllBands.append(DetailBandClass(Name: "Secret Weapons", Genre: "Rock", SongOneURL: "https://www.youtube.com/watch?v=qdXx-71gNcc", SongTwoURL: "", SongThreeURL: "", SongFourURL: "", SongFiveURL: "", SongOneName: "Something New", SongTwoName: "", SongThreeName: "", SongFourName: "", SongFiveName: "", Day: "Day 3"))
            arrayOfAllBands.append(DetailBandClass(Name: "Slumberjack", Genre: "Hip Hop", SongOneURL: "https://www.youtube.com/watch?v=ip9NLvm8Ck4", SongTwoURL: "https://www.youtube.com/watch?v=JyrbrYsdf7M", SongThreeURL: "https://www.youtube.com/watch?v=pt0a5sx9pTE", SongFourURL: "https://www.youtube.com/watch?v=kZwmj08xHDY", SongFiveURL: "https://www.youtube.com/user/alisonwonderlanddj", SongOneName: "Body Cry", SongTwoName: "Enigma", SongThreeName: "Horus", SongFourName: "The Others", SongFiveName: "Naked", Day: "Day 3"))
            arrayOfAllBands.append(DetailBandClass(Name: "Snails", Genre: "Electronic", SongOneURL: "https://www.youtube.com/watch?v=HanBb8FonWs", SongTwoURL: "https://www.youtube.com/watch?v=wFE3d6de31w", SongThreeURL: "https://www.youtube.com/watch?v=aLTh1TzbuCw", SongFourURL: "https://www.youtube.com/watch?v=Fr41-nZZCag", SongFiveURL: "https://www.youtube.com/watch?v=UfI3333AaN8", SongOneName: "Frogbass", SongTwoName: "Slugz", SongThreeName: "Pump This", SongFourName: "Funk With Me", SongFiveName: "Dirty Raxxx ft. Panther", Day: "Day 3"))
            arrayOfAllBands.append(DetailBandClass(Name: "St. Lucia", Genre: "Alternative", SongOneURL: "https://www.youtube.com/watch?v=EmsyXRw3KuI", SongTwoURL: "https://www.youtube.com/watch?v=lDKJ29357FU", SongThreeURL: "https://www.youtube.com/watch?v=7HPMK9Uxq3I", SongFourURL: "https://www.youtube.com/watch?v=tBlreotoFKg", SongFiveURL: "https://www.youtube.com/watch?v=ocA-9CnVzXY", SongOneName: "Before The Dive", SongTwoName: "Dancing On Glass", SongThreeName: "Elevate", SongFourName: "September", SongFiveName: "All Eyes On You", Day: "Day 3"))
            arrayOfAllBands.append(DetailBandClass(Name: "The Front Bottoms", Genre: "Alternative", SongOneURL: "https://www.youtube.com/watch?v=-1rzsT2t2YY", SongTwoURL: "https://www.youtube.com/watch?v=_n-8iPfI-o4", SongThreeURL: "https://www.youtube.com/watch?v=u-Qw6T_FKMc", SongFourURL: "https://www.youtube.com/watch?v=YxZ5B1lVXPc", SongFiveURL: "https://www.youtube.com/watch?v=XII7af9SrLI", SongOneName: "Twin Size Mattress", SongTwoName: "Cough It Out", SongThreeName: "Flashlight", SongFourName: "Funny You Should Ask", SongFiveName: "West Virginia", Day: "Day 3"))
            arrayOfAllBands.append(DetailBandClass(Name: "The Joy Formidable", Genre: "Alternative", SongOneURL: "https://www.youtube.com/watch?v=a2BUEzdjfpY", SongTwoURL: "https://www.youtube.com/watch?v=mpKlLs_Xrcw", SongThreeURL: "https://www.youtube.com/watch?v=W66yhfMb4d0", SongFourURL: "https://www.youtube.com/watch?v=gfZXQ16yPPU", SongFiveURL: "https://www.youtube.com/watch?v=_Y9nEPttcJ4", SongOneName: "Whirring", SongTwoName: "Endtapes", SongThreeName: "Cradle", SongFourName: "The Greatest Light is the Greatest Shade", SongFiveName: "Wolf’s Law", Day: "Day 3"))
            arrayOfAllBands.append(DetailBandClass(Name: "The Strumbellas", Genre: "", SongOneURL: "https://www.youtube.com/watch?v=F9kXstb9FF4", SongTwoURL: "https://www.youtube.com/watch?v=6fx3atxPp8M", SongThreeURL: "https://www.youtube.com/watch?v=1Gm-y6c925s", SongFourURL: "https://www.youtube.com/watch?v=BI7bp7W-zjI", SongFiveURL: "https://www.youtube.com/watch?v=SjxdvGJDYm8", SongOneName: "Spirits", SongTwoName: "Shovels & Dirt", SongThreeName: "End of an Era", SongFourName: "Sailing", SongFiveName: "In This Life", Day: "Day 3"))
            arrayOfAllBands.append(DetailBandClass(Name: "Tor Miller", Genre: "Alternative", SongOneURL: "https://www.youtube.com/watch?v=oyK-kD55s4o", SongTwoURL: "https://www.youtube.com/watch?v=Kwoi3LZU2-0", SongThreeURL: "https://www.youtube.com/watch?v=TkOPzg2IbWQ", SongFourURL: "https://www.youtube.com/watch?v=jabRB8LSAPE", SongFiveURL: "https://www.youtube.com/watch?v=Lz4BlW-Z4EU", SongOneName: "Carter & Cash", SongTwoName: "Midnight", SongThreeName: "Headlights", SongFourName: "Now And Again", SongFiveName: "Hold the Phone", Day: "Day 3"))
            arrayOfAllBands.append(DetailBandClass(Name: "Tory Lanez", Genre: "Hip Hop", SongOneURL: "https://www.youtube.com/watch?v=xUq1rZ7mmns", SongTwoURL: "https://www.youtube.com/watch?v=itp_3yxTOEI", SongThreeURL: "https://www.youtube.com/watch?v=REBFAZSITgk", SongFourURL: "https://www.youtube.com/watch?v=7K239Z8YzWI", SongFiveURL: "https://www.youtube.com/watch?v=N1EWfaESMws", SongOneName: "Say It", SongTwoName: "LA Confidential", SongThreeName: "Traphouse", SongFourName: "B.L.O.W.", SongFiveName: "Real Adresses", Day: "Day 3"))
            arrayOfAllBands.append(DetailBandClass(Name: "Two Door Cinema Club", Genre: "Alternative", SongOneURL: "https://www.youtube.com/watch?v=YXwYJyrKK5A", SongTwoURL: "https://www.youtube.com/watch?v=Wxu02vp_Vm0", SongThreeURL: "https://www.youtube.com/watch?v=LLK4oaXUuLg", SongFourURL: "https://www.youtube.com/watch?v=bJDCMth8poM", SongFiveURL: "https://www.youtube.com/watch?v=YNXybY2DtwM", SongOneName: "What You Know", SongTwoName: "Something Good Can Come", SongThreeName: "Undercover Martyn", SongFourName: "I Can Talk", SongFiveName: "Sleep Alone", Day: "Day 3"))
            arrayOfAllBands.append(DetailBandClass(Name: "Vic Mensa", Genre: "Hip Hop", SongOneURL: "https://www.youtube.com/watch?v=fP8FMdVcCQQ", SongTwoURL: "https://www.youtube.com/watch?v=5jUGAVUwhRU", SongThreeURL: "https://www.youtube.com/watch?v=ybMEINc5KRw", SongFourURL: "https://www.youtube.com/watch?v=QTOn91OeMbw", SongFiveURL: "https://www.youtube.com/watch?v=jAnbqTa2n0k", SongOneName: "U Mad", SongTwoName: "Down On My Luck", SongThreeName: "No Chill", SongFourName: "Wimme Nah", SongFiveName: "Pasadena", Day: "Day 3"))
            arrayOfAllBands.append(DetailBandClass(Name: "Wolf Alice", Genre: "Alternative", SongOneURL: "https://www.youtube.com/watch?v=z71df68qLp0", SongTwoURL: "https://www.youtube.com/watch?v=g6vEE3Plk48", SongThreeURL: "https://www.youtube.com/watch?v=uq_vRu24vV8", SongFourURL: "https://www.youtube.com/watch?v=ZpomZoueWa0", SongFiveURL: "https://www.youtube.com/watch?v=9bsbGAQcICU", SongOneName: "Moaning Lisa Smile", SongTwoName: "Giant Peach", SongThreeName: "Freazy", SongFourName: "You’re a Germ", SongFiveName: "Your Loves Whore", Day: "Day 3"))
            arrayOfAllBands.append(DetailBandClass(Name: "X Ambassadors", Genre: "Alternative", SongOneURL: "https://www.youtube.com/watch?v=1u-niluB8HI", SongTwoURL: "https://www.youtube.com/watch?v=EzP5KsYSGD0", SongThreeURL: "https://www.youtube.com/watch?v=V0lw3qylVfY", SongFourURL: "https://www.youtube.com/watch?v=tGr_cyThHkc", SongFiveURL: "https://www.youtube.com/watch?v=aqXW57WM9TA", SongOneName: "Renegades", SongTwoName: "Unconsolable", SongThreeName: "Unsteady", SongFourName: "Litost", SongFiveName: "Jungle", Day: "Day 3"))
        }
        if title1 == "Day 4"
        {
            arrayOfAllBands.append(DetailBandClass(Name: "Adventure Club", Genre: "House", SongOneURL: "https://www.youtube.com/watch?v=ZeaIvjoH1FY", SongTwoURL: "https://www.youtube.com/watch?v=09wdQP1FFR0", SongThreeURL: "https://www.youtube.com/watch?v=4ZYm0anhvLg", SongFourURL: "https://www.youtube.com/watch?v=WinkoZiOYQc", SongFiveURL: "https://www.youtube.com/watch?v=_y8p6uQDH4s", SongOneName: "Crave You", SongTwoName: "Gold (feat. Yuna)", SongThreeName: " Retro City", SongFourName: "Wonder (Feat. The Kite String Tangle)", SongFiveName: "Rise & Fall (feat. Krewella)", Day: "Day 4"))
            arrayOfAllBands.append(DetailBandClass(Name: "Aurora", Genre: "Pop", SongOneURL: "https://www.youtube.com/watch?v=06ht9MyJLT4", SongTwoURL: "https://www.youtube.com/watch?v=d_HlPboLRL8", SongThreeURL: "https://www.youtube.com/watch?v=SYKU7DfEJT4", SongFourURL: "https://www.youtube.com/watch?v=5AWHALoCzPM", SongFiveURL: "https://www.youtube.com/watch?v=FA39yqwnX98", SongOneName: "Running With The Wolves", SongTwoName: "Runaway", SongThreeName: "Half The World Away", SongFourName: "Under Stars", SongFiveName: "Ordinary World", Day: "Day 4"))
            arrayOfAllBands.append(DetailBandClass(Name: "Banners", Genre: "Alternative", SongOneURL: "https://www.youtube.com/watch?v=ZXorliBQMxg", SongTwoURL: "https://www.youtube.com/watch?v=uaLblVmnNL4", SongThreeURL: "https://www.youtube.com/watch?v=U5wjOYg3SJQ", SongFourURL: "https://www.youtube.com/watch?v=6pF4VjwrkVg", SongFiveURL: "https://www.youtube.com/watch?v=0Tz-XVymk04", SongOneName: "Start A Riot", SongTwoName: "Shine A Light", SongThreeName: "Ghosts", SongFourName: "Gold Dust", SongFiveName: "Back When We Had Nothing", Day: "Day 4"))
            arrayOfAllBands.append(DetailBandClass(Name: "Bloc Party", Genre: "Rock", SongOneURL: "https://www.youtube.com/watch?v=vdkmhquF60o", SongTwoURL: "https://www.youtube.com/watch?v=2R6S5CJWlco", SongThreeURL: "https://www.youtube.com/watch?v=-oRlpGyI1rg", SongFourURL: "https://www.youtube.com/watch?v=CdBt3n1MtFM", SongFiveURL: "https://www.youtube.com/watch?v=dzZQJZdcCU4", SongOneName: "Banquet", SongTwoName: "Helicopter", SongThreeName: "This Modern Love", SongFourName: "Like Eating Glass", SongFiveName: "So Here We Are", Day: "Day 4"))
            arrayOfAllBands.append(DetailBandClass(Name: "Bryson Tiller", Genre: "Hip Hop", SongOneURL: "https://www.youtube.com/watch?v=iOpJywrdCuQ", SongTwoURL: "https://www.youtube.com/watch?v=d7cVLE4SaN0", SongThreeURL: "https://www.youtube.com/watch?v=WJ47cpZE-wg", SongFourURL: "", SongFiveURL: "", SongOneName: "Exchange", SongTwoName: "Don’t (J. Louis Remix)", SongThreeName: "Dreams", SongFourName: "", SongFiveName: "", Day: "Day 4"))
            arrayOfAllBands.append(DetailBandClass(Name: "Burns", Genre: "Electronic", SongOneURL: "https://www.youtube.com/watch?v=sMRUgw6ODDg", SongTwoURL: "https://www.youtube.com/watch?v=Q0hfrxg7fa8", SongThreeURL: "", SongFourURL: "", SongFiveURL: "", SongOneName: "Lies", SongTwoName: "First Move", SongThreeName: "", SongFourName: "", SongFiveName: "", Day: "Day 4"))
            arrayOfAllBands.append(DetailBandClass(Name: "Burns", Genre: "Electronic", SongOneURL: "https://www.youtube.com/watch?v=sMRUgw6ODDg", SongTwoURL: "https://www.youtube.com/watch?v=Q0hfrxg7fa8", SongThreeURL: "", SongFourURL: "", SongFiveURL: "", SongOneName: "Lies", SongTwoName: "First Move", SongThreeName: "", SongFourName: "", SongFiveName: "", Day: "Day 4"))
            arrayOfAllBands.append(DetailBandClass(Name: "Die Antwoord", Genre: "Hip Hop", SongOneURL: "https://www.youtube.com/watch?v=uMK0prafzw0", SongTwoURL: "https://www.youtube.com/watch?v=8Uee_mcxvrw", SongThreeURL: "https://www.youtube.com/watch?v=cegdR0GiJl4", SongFourURL: "https://www.youtube.com/watch?v=BXx7LZdrqHE", SongFiveURL: "https://www.youtube.com/watch?v=AIXUgtNC4Kc", SongOneName: "Ugly Boy", SongTwoName: "I Fink U Freaky", SongThreeName: "Enter The Ninja", SongFourName: "Baby’s On Fire", SongFiveName: "Fatty Boom Boom", Day: "Day 4"))
            arrayOfAllBands.append(DetailBandClass(Name: "D.R.A.M.", Genre: "Rap", SongOneURL: "https://www.youtube.com/watch?v=nUv3vM7iMTo", SongTwoURL: "https://www.youtube.com/watch?v=_ZeaSIMiB7k", SongThreeURL: "https://www.youtube.com/watch?v=rKRtyBB0Vho", SongFourURL: "https://www.youtube.com/watch?v=kdQ1Gj3y13s", SongFiveURL: "https://www.youtube.com/watch?v=EIPwOIamXmI", SongOneName: "Signals", SongTwoName: "CareTaker", SongThreeName: "I Luv It", SongFourName: "Mind Gone", SongFiveName: "2$", Day: "Day 4"))
            arrayOfAllBands.append(DetailBandClass(Name: "Ellie Goulding", Genre: "Pop", SongOneURL: "https://www.youtube.com/watch?v=0NKUpo_xKyQ", SongTwoURL: "https://www.youtube.com/watch?v=BBxjC9w_Cj0", SongThreeURL: "https://www.youtube.com/watch?v=rNpBahr49mA", SongFourURL: "https://www.youtube.com/watch?v=5hzgS9s-tE8", SongFiveURL: "https://www.youtube.com/watch?v=CGyEd0aKWZE", SongOneName: "Lights", SongTwoName: "Love Me Like You Do", SongThreeName: "Figure 8", SongFourName: "Anything Could Happen", SongFiveName: "Burn", Day: "Day 4"))
            arrayOfAllBands.append(DetailBandClass(Name: "Fidlar", Genre: "Rock", SongOneURL: "https://www.youtube.com/watch?v=iJy8VgB83OQ", SongTwoURL: "https://www.youtube.com/watch?v=BYbJmQj5VkE", SongThreeURL: "https://www.youtube.com/watch?v=ztlZq_qqu-4", SongFourURL: "https://www.youtube.com/watch?v=BB8z08_8uhM", SongFiveURL: "https://www.youtube.com/watch?v=2mV239VN1-U", SongOneName: "40oz On Repeat", SongTwoName: "No Waves", SongThreeName: "West Coast", SongFourName: "Cheap Beer", SongFiveName: "Wake Bake Skate", Day: "Day 4"))
            arrayOfAllBands.append(DetailBandClass(Name: "Flatbush Zombies", Genre: "Hip Hop", SongOneURL: "https://www.youtube.com/watch?v=xA3Ov1RP2cw", SongTwoURL: "https://www.youtube.com/watch?v=pxplVYIN1Fc", SongThreeURL: "https://www.youtube.com/watch?v=Mhvyi1c6Gkw", SongFourURL: "https://www.youtube.com/watch?v=i9X92OV4o48", SongFiveURL: "https://www.youtube.com/watch?v=NwaE6UpMk5s", SongOneName: "New Phone, Who Dis?", SongTwoName: "This Is It", SongThreeName: "R.I.P.C.D.", SongFourName: "Your Favorite Rap Song", SongFiveName: "Bounce", Day: "Day 4"))
            arrayOfAllBands.append(DetailBandClass(Name: "Flume", Genre: "Electronic", SongOneURL: "https://www.youtube.com/watch?v=-KPnyf8vwXI", SongTwoURL: "https://www.youtube.com/watch?v=6vopR3ys8Kw", SongThreeURL: "https://www.youtube.com/watch?v=X_H3cIsenBQ", SongFourURL: "https://www.youtube.com/watch?v=4fAzM5cI5FM", SongFiveURL: "https://www.youtube.com/watch?v=peRS3KGNxoY", SongOneName: "Never Be Like You", SongTwoName: "Drop The Game", SongThreeName: "Holdin On", SongFourName: "Smoke & Retribution", SongFiveName: "Insane", Day: "Day 4"))
            arrayOfAllBands.append(DetailBandClass(Name: "Haim", Genre: "Rock", SongOneURL: "https://www.youtube.com/watch?v=AIjVpRAXK18", SongTwoURL: "https://www.youtube.com/watch?v=eSlmgr15Yh0", SongThreeURL: "https://www.youtube.com/watch?v=Ljg6g7BAdQo", SongFourURL: "https://www.youtube.com/watch?v=kiqIush2nTA", SongFiveURL: "https://www.youtube.com/watch?v=1TffpkE2GU4", SongOneName: "Falling", SongTwoName: "My Song 5", SongThreeName: "If I Could Change Your Mind", SongFourName: "Don’t Save Me ", SongFiveName: "The Wire", Day: "Day 4"))
            arrayOfAllBands.append(DetailBandClass(Name: "Halsey", Genre: "Electronic", SongOneURL: "https://www.youtube.com/watch?v=JGulAZnnTKA", SongTwoURL: "https://www.youtube.com/watch?v=1rfSHisyHdc", SongThreeURL: "https://www.youtube.com/watch?v=b-eYbUVZedY", SongFourURL: "https://www.youtube.com/watch?v=ao4o-XRU_KM", SongFiveURL: "https://www.youtube.com/watch?v=zRHNi3QfFlE", SongOneName: "Colors", SongTwoName: "Castle", SongThreeName: "New Americana", SongFourName: "Ghost", SongFiveName: "Gasoline", Day: "Day 4"))
            arrayOfAllBands.append(DetailBandClass(Name: "Jackal", Genre: "Rock", SongOneURL: "https://www.youtube.com/watch?v=mC-Zq0AIkiI", SongTwoURL: "https://www.youtube.com/watch?v=mC-Zq0AIkiI", SongThreeURL: "https://www.youtube.com/watch?v=m6z5mo4VQ5M", SongFourURL: "https://www.youtube.com/watch?v=VLbNCvcMpIE", SongFiveURL: "https://www.youtube.com/watch?v=SduvoFSgWeY", SongOneName: "ShakeDown", SongTwoName: "Let Me Tell you Something", SongThreeName: "Carbomb", SongFourName: "Netflix N Kill", SongFiveName: "Sunny Side Of The Day", Day: "Day 4"))
            arrayOfAllBands.append(DetailBandClass(Name: "Lapsley", Genre: "Electronic", SongOneURL: "https://www.youtube.com/watch?v=Kn5LXZv11ww", SongTwoURL: "https://www.youtube.com/watch?v=wXmaDGAlLvU", SongThreeURL: "https://www.youtube.com/watch?v=Pisxp5Gi3co", SongFourURL: "https://www.youtube.com/watch?v=uD7_Vt5q2q8", SongFiveURL: "https://www.youtube.com/watch?v=HyMfMYRpHUg", SongOneName: "Hurt Me ", SongTwoName: "Love Is Blind", SongThreeName: "Falling Short", SongFourName: "Station", SongFiveName: "Painter", Day: "Day 4 "))
            arrayOfAllBands.append(DetailBandClass(Name: "LCD SoundSystem", Genre: "Electronic", SongOneURL: "https://www.youtube.com/watch?v=OoA0cTC228M", SongTwoURL: "https://www.youtube.com/watch?v=Cj8JrQ9w5jY", SongThreeURL: "https://www.youtube.com/watch?v=-eohHwsplvY", SongFourURL: "https://www.youtube.com/watch?v=6xG4oFny2Pk", SongFiveURL: "https://www.youtube.com/watch?v=9L8yEDcZ-QI", SongOneName: "Dance Yrself Clean", SongTwoName: "Daft Punk Is Playing At My House", SongThreeName: "New York, I Love You But You’re...", SongFourName: "Losing MyEdge", SongFiveName: "All My Friends", Day: "Day 4"))
            arrayOfAllBands.append(DetailBandClass(Name: "Lindsey Sirling", Genre: "Electronic", SongOneURL: "https://www.youtube.com/watch?v=aHjpOzsQ9YI", SongTwoURL: "https://www.youtube.com/watch?v=49tpIMDy9BE", SongThreeURL: "https://www.youtube.com/watch?v=jvipPYFebWc", SongFourURL: "https://www.youtube.com/watch?v=aE2GCa-_nyU", SongFiveURL: "https://www.youtube.com/watch?v=sf6LD2B_kDQ", SongOneName: "Crysatallize", SongTwoName: "Shader Me", SongThreeName: "Round Table Rival", SongFourName: "Radioactive", SongFiveName: "Elements", Day: "Day 4"))
            arrayOfAllBands.append(DetailBandClass(Name: "Local Natives", Genre: "Rock", SongOneURL: "https://www.youtube.com/watch?v=mN-CqIytN2U", SongTwoURL: "https://www.youtube.com/watch?v=NmefFcRJbXE", SongThreeURL: "https://www.youtube.com/watch?v=6hhE_sqJG3g", SongFourURL: "https://www.youtube.com/watch?v=L1dFjloBZYo", SongFiveURL: "https://www.youtube.com/watch?v=h2zWfxW60z0", SongOneName: "Mt. Washington", SongTwoName: "Wide Eyes", SongThreeName: "Who Knows Who Cares", SongFourName: "Breakers", SongFiveName: "Heavy Feet", Day: "Day 4"))
            arrayOfAllBands.append(DetailBandClass(Name: "Louis The Child", Genre: "Electronic", SongOneURL: "https://www.youtube.com/watch?v=Wdjeq9t_YNg", SongTwoURL: "https://www.youtube.com/watch?v=ZtSu_m0L4co", SongThreeURL: "https://www.youtube.com/watch?v=pZzVgNn3y68", SongFourURL: "https://www.youtube.com/watch?v=R65s3mPGeQk", SongFiveURL: "https://www.youtube.com/watch?v=FYBHCQsHC0g", SongOneName: "It’s Strange Feat", SongTwoName: "Oh Wonder", SongThreeName: "Zella Day", SongFourName: "It’s Strange", SongFiveName: "All For You", Day: "Day 4"))
            arrayOfAllBands.append(DetailBandClass(Name: "Marian Hill", Genre: "Alternative", SongOneURL: "https://www.youtube.com/watch?v=1VFDYHJYtsI", SongTwoURL: "https://www.youtube.com/watch?v=bnVIQmPJ_X8", SongThreeURL: "https://www.youtube.com/watch?v=4DiqkL32IYo", SongFourURL: "https://www.youtube.com/watch?v=8-FUkhVtveU", SongFiveURL: "https://www.youtube.com/watch?v=az00U-Scql4", SongOneName: "One Time", SongTwoName: "Love It", SongThreeName: "Got It", SongFourName: "Lips", SongFiveName: "Breath Into Me", Day: "Day 4"))
            arrayOfAllBands.append(DetailBandClass(Name: "Mija", Genre: "Electronic", SongOneURL: "https://www.youtube.com/watch?v=eg1fAnrtaAs", SongTwoURL: "https://www.youtube.com/watch?v=jsCeco5D92A", SongThreeURL: "https://www.youtube.com/watch?v=QiBimQB7Elw", SongFourURL: "", SongFiveURL: "", SongOneName: "Major Lazer ft. Wild Belle - b2gether (MIJA REMIX)", SongTwoName: "DJ Snake - Middle (Mija Remix)", SongThreeName: "Darren Styles - Come Running (Mija Remix)", SongFourName: "", SongFiveName: "", Day: "Day 4"))
            arrayOfAllBands.append(DetailBandClass(Name: "Muna", Genre: "Pop", SongOneURL: "https://www.youtube.com/watch?v=Lnps91BM-cs", SongTwoURL: "https://www.youtube.com/watch?v=o2y3y6xJeo0", SongThreeURL: "https://www.youtube.com/watch?v=ts2vVkH_JBM", SongFourURL: "https://www.youtube.com/watch?v=K6RPdr_jHo4", SongFiveURL: "", SongOneName: "Winter Break", SongTwoName: "Loud Speaker", SongThreeName: "Promise", SongFourName: "So Special", SongFiveName: "", Day: "Day 4"))
            arrayOfAllBands.append(DetailBandClass(Name: "Oh Wonder", Genre: "Pop", SongOneURL: "https://www.youtube.com/watch?v=VgwcPiCjQ-0", SongTwoURL: "https://www.youtube.com/watch?v=zLAhRiUeJ8E", SongThreeURL: "https://www.youtube.com/watch?v=j9FfYWp_d5w", SongFourURL: "https://www.youtube.com/watch?v=_w5jPT8LMF0", SongFiveURL: "https://www.youtube.com/watch?v=vppNNO7nDuk", SongOneName: "Lose It", SongTwoName: "With Out You", SongThreeName: "Technicolor Beats", SongFourName: "Drive", SongFiveName: "Body Gold", Day: "Day 4"))
            arrayOfAllBands.append(DetailBandClass(Name: "Panama Wedding", Genre: "Pop", SongOneURL: "https://www.youtube.com/watch?v=_q4P0SjIqoU", SongTwoURL: "https://www.youtube.com/watch?v=Gf7zUBazXIY", SongThreeURL: "https://www.youtube.com/watch?v=84F6LKUUuzA", SongFourURL: "https://www.youtube.com/watch?v=_UengtRHo2U", SongFiveURL: "https://www.youtube.com/watch?v=b0Brbd76twM", SongOneName: "All Of The People", SongTwoName: "Infinite High", SongThreeName: "Feels Like Summer", SongFourName: "Into Focus", SongFiveName: "Younger Love", Day: "Day 4"))
            arrayOfAllBands.append(DetailBandClass(Name: "Seven Lions", Genre: "House", SongOneURL: "https://www.youtube.com/watch?v=SKlbCjNCDn4", SongTwoURL: "https://www.youtube.com/watch?v=y1hWi-vgoaU", SongThreeURL: "https://www.youtube.com/watch?v=Rk-SrePDxfQ", SongFourURL: "https://www.youtube.com/watch?v=EKqHnwKlLNE", SongFiveURL: "https://www.youtube.com/watch?v=ULqdjtDI-bs", SongOneName: "Don’t Leave", SongTwoName: "Days to Come", SongThreeName: "Stranger's", SongFourName: "Falling Away", SongFiveName: "Worlds Apart", Day: "Day 4 "))
            arrayOfAllBands.append(DetailBandClass(Name: "Silversun Pickups", Genre: "Rock", SongOneURL: "https://www.youtube.com/watch?v=AG8fugqFn9Q", SongTwoURL: "https://www.youtube.com/watch?v=z-mxBDuRaZ8", SongThreeURL: "https://www.youtube.com/watch?v=x4IDM3ltTYo", SongFourURL: "https://www.youtube.com/watch?v=Ol4Dko3rw28", SongFiveURL: "https://www.youtube.com/watch?v=u33g0vlGaPM", SongOneName: "Panic Swithc", SongTwoName: "Lazy Eye", SongThreeName: "Night Light", SongFourName: "Circadian Rhythm", SongFiveName: "Dots and Dashes", Day: "Day 4"))
            arrayOfAllBands.append(DetailBandClass(Name: "Sir The Baptist", Genre: "Rap", SongOneURL: "https://www.youtube.com/watch?v=z6cglPRmqC4", SongTwoURL: "https://www.youtube.com/watch?v=4RTU38yfZtw", SongThreeURL: "https://www.youtube.com/watch?v=Tuzpn01E6i0", SongFourURL: "", SongFiveURL: "", SongOneName: "Raise Hell", SongTwoName: "Creflo Almighty Dollar", SongThreeName: "Wake up", SongFourName: "", SongFiveName: "", Day: "Day 4"))
            arrayOfAllBands.append(DetailBandClass(Name: "Smino", Genre: "Rap", SongOneURL: "https://www.youtube.com/watch?v=6PUp4Eyz8f8", SongTwoURL: "https://www.youtube.com/watch?v=ODBMcd0rpCY", SongThreeURL: "https://www.youtube.com/watch?v=nIkhDBrsSts", SongFourURL: "https://www.youtube.com/watch?v=UKUKoG_4-6E", SongFiveURL: "https://www.youtube.com/watch?v=EkxQJf7ZVvo", SongOneName: "Oxegyn", SongTwoName: "Ruby Red", SongThreeName: "Raw", SongFourName: "Runnin’", SongFiveName: "blkjuptr", Day: "Day 4"))
            arrayOfAllBands.append(DetailBandClass(Name: "Snakehips", Genre: "Electronic", SongOneURL: "https://www.youtube.com/watch?v=I3mrYxPLSH4", SongTwoURL: "https://www.youtube.com/watch?v=EWb8oUwubWg", SongThreeURL: "https://www.youtube.com/watch?v=kA2BSluxql8", SongFourURL: "https://www.youtube.com/watch?v=w7yqvl9FJHg", SongFiveURL: "https://www.youtube.com/watch?v=ftuU6dMe3ck", SongOneName: "All My Friends", SongTwoName: "Forever, Part II", SongThreeName: "Days With You", SongFourName: "On & On", SongFiveName: "Money On Me", Day: "Day 4"))
            arrayOfAllBands.append(DetailBandClass(Name: "Third Eye Blind", Genre: "Alternative", SongOneURL: "https://www.youtube.com/watch?v=MyjTrwOMSO4", SongTwoURL: "https://www.youtube.com/watch?v=QdgCajndgNw", SongThreeURL: "https://www.youtube.com/watch?v=Femqf_Mel4U", SongFourURL: "https://www.youtube.com/watch?v=6kiHBFwGsUE", SongFiveURL: "https://www.youtube.com/watch?v=lXRLEyIoJZA", SongOneName: "Semi-Charmed Life", SongTwoName: "Jumper", SongThreeName: "How It’s Going to Be", SongFourName: "Never Let You Go", SongFiveName: "Motorcycle Drive By", Day: "Day 4"))
            arrayOfAllBands.append(DetailBandClass(Name: "Unified Highway", Genre: "Alternative", SongOneURL: "https://www.youtube.com/watch?v=wF_BFD6wZvo", SongTwoURL: "https://www.youtube.com/watch?v=fE-vocNGrIc", SongThreeURL: "https://www.youtube.com/watch?v=L7encbwe82M", SongFourURL: "https://www.youtube.com/watch?v=iTaMVRGxBC0", SongFiveURL: "https://www.youtube.com/watch?v=rjuX-tTesbg", SongOneName: "My Only  ", SongTwoName: "Stand Proud", SongThreeName: "Never the Same", SongFourName: "Same Thing Coming", SongFiveName: "Rainy Day in Autumn", Day: "Day 4"))
            arrayOfAllBands.append(DetailBandClass(Name: "VHS Collection", Genre: "Rock", SongOneURL: "https://www.youtube.com/watch?v=25mVCCDqI34", SongTwoURL: "https://www.youtube.com/watch?v=LNMTL2e5tXg", SongThreeURL: "https://www.youtube.com/watch?v=wZQiIi7DggY", SongFourURL: "", SongFiveURL: "", SongOneName: "Late Night", SongTwoName: "Far Hills Cider", SongThreeName: "Lean", SongFourName: "", SongFiveName: "", Day: "Day 4"))
            arrayOfAllBands.append(DetailBandClass(Name: "Vince Staples", Genre: "Hip Hop", SongOneURL: "https://www.youtube.com/watch?v=mb6Jc4juSF8", SongTwoURL: "https://www.youtube.com/watch?v=4fAzM5cI5FM", SongThreeURL: "https://www.youtube.com/watch?v=NJLfCBBcZAo", SongFourURL: "https://www.youtube.com/watch?v=5OAYMMod9Wo", SongFiveURL: "https://www.youtube.com/watch?v=bn15IvVrprw", SongOneName: "Norf Norf", SongTwoName: "Smoke & Retribution", SongThreeName: "Blue Suede", SongFourName: "Señorita", SongFiveName: "Lift Me Up", Day: "Day 4"))
            arrayOfAllBands.append(DetailBandClass(Name: "Years & Years", Genre: "Indie Pop", SongOneURL: "https://www.youtube.com/watch?v=GNb4FBawH_U", SongTwoURL: "https://www.youtube.com/watch?v=g_uoH6hJilc", SongThreeURL: "https://www.youtube.com/watch?v=hXTAn4ELEwM", SongFourURL: "https://www.youtube.com/watch?v=wf_ySBlZjKw", SongFiveURL: "https://www.youtube.com/watch?v=VjT4BzLTaJU", SongOneName: "Desire", SongTwoName: "King", SongThreeName: "Shine", SongFourName: "Eyes Shut", SongFiveName: "Real", Day: "Day 4"))
            arrayOfAllBands.append(DetailBandClass(Name: "Yellow Claw", Genre: "Electronic", SongOneURL: "https://www.youtube.com/watch?v=SWx9mI2gTwI", SongTwoURL: "https://www.youtube.com/watch?v=vyc92rAYAlA", SongThreeURL: "https://www.youtube.com/watch?v=AqUKf2sqjd0", SongFourURL: "https://www.youtube.com/watch?v=oIwFJNguQgY", SongFiveURL: "https://www.youtube.com/watch?v=rX4g0sxDCEw", SongOneName: "Slow Down", SongTwoName: "Colors", SongThreeName: "Lick Dat", SongFourName: "Shotgun", SongFiveName: "DJ Turn It Up", Day: "Day 4"))
            arrayOfAllBands.append(DetailBandClass(Name: "Zhu", Genre: "House", SongOneURL: "https://www.youtube.com/watch?v=BwWzSyxNc9I", SongTwoURL: "https://www.youtube.com/watch?v=ThUtI7LB17Y", SongThreeURL: "https://www.youtube.com/watch?v=5_ARibfCMhw", SongFourURL: "https://www.youtube.com/watch?v=qv9YI8Oqs30", SongFiveURL: "https://www.youtube.com/watch?v=9fOfplgIYEY", SongOneName: "Faded", SongTwoName: "Cocaine Model", SongThreeName: "In the Morning", SongFourName: "Working For It", SongFiveName: "Paradise Awaits", Day: "Day 4"))
        }
//        if arrayOfDays[selectedRow!] = "Day 1"
//        {
//            
//        }
        //tableView(bandsInSelectedDayTableView, titleForHeaderInSection: arrayOfBandsByDay.name)

    }
    
    func tableView(tableView: UITableView, cellForRowAtIndexPath indexPath: NSIndexPath) -> UITableViewCell
    {
        let myTableViewCell = bandsInSelectedDayTableView.dequeueReusableCellWithIdentifier("myCell3", forIndexPath: indexPath)
        myTableViewCell.textLabel?.text = arrayOfAllBands[indexPath.row].name
        return myTableViewCell
        
        
    }
    func tableView(tableView: UITableView, numberOfRowsInSection section: Int) -> Int
    {
        return arrayOfAllBands.count
    }
    
    override func prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?)
    {
        let detailVC = segue.destinationViewController as! SongsBySelectedBand
        let selectedRow = bandsInSelectedDayTableView.indexPathForSelectedRow?.row
        detailVC.band = arrayOfAllBands[selectedRow!] //detailVC.superhero(reciever) = superheros[selectedRow](quarterback)
    }



}
